SSAnne_CaptainsOffice_Text_CaptainIFeelSeasick::
    .string "CAPTAIN: Ooargh…\n"
    .string "I feel hideous…\l"
    .string "Urrp! Seasick…$"

SSAnne_CaptainsOffice_Text_RubbedCaptainsBack::
    .string "{PLAYER} rubbed the CAPTAIN's\n"
    .string "back!\p"
    .string "Rub-rub…\n"
    .string "Rub-rub…$"

SSAnne_CaptainsOffice_Text_ThankYouHaveHMForCut::
    .string "CAPTAIN: Whew! Thank you!\n"
    .string "I'm feeling much better now.\p"
    .string "I know! You can have this!\n"
    .string "This HIDDEN MACHINE!$"

SSAnne_CaptainsOffice_Text_ObtainedHM01FromCaptain::
    .string "{PLAYER} obtained HM01\n"
    .string "from the CAPTAIN!$"

SSAnne_CaptainsOffice_Text_AlsoTakeEdgelord::
    .string "CAPTAIN: And take this, too!\n"
    .string "I call it the EDGELORD.$"

SSAnne_CaptainsOffice_Text_ObtainedEdgelordFromCaptain::
    .string "{PLAYER} obtained the EDGELORD\n"
    .string "from the CAPTAIN!$"

SSAnne_CaptainsOffice_Text_ExplainCut::
    .string "Use the EDGELORD from your BAG\n"
    .string "to chop down small trees.\p"
    .string "Once you earn the right BADGE,\n"
    .string "try the trees by VERMILION CITY.$"

SSAnne_CaptainsOffice_Text_SSAnneWillSetSailSoon::
    .string "CAPTAIN: …Whew!\p"
    .string "Now that I'm not sick anymore,\n"
    .string "I guess it's time.\p"
    .string "The S.S. ANNE will set sail soon!\p"
    .string "Farewell, until our return to\n"
    .string "VERMILION CITY!$"

SSAnne_CaptainsOffice_Text_YouHaveNoRoomForThis::
    .string "Oh, no!\n"
    .string "You have no room for this!$"

SSAnne_CaptainsOffice_Text_YuckShouldntHaveLooked::
    .string "Yuck!\n"
    .string "Shouldn't have looked!$"

SSAnne_CaptainsOffice_Text_HowToConquerSeasickness::
    .string "How to Conquer Seasickness…\n"
    .string "The CAPTAIN's reading this!$"
