Route2_EastBuilding_Text_GiveHM05IfSeen10Mons::
    .string "Hi! Remember me?\n"
    .string "I'm one of PROF. OAK's AIDES.\p"
    .string "If your POKéDEX has complete data\n"
    .string "on ten species, I'm supposed to\l"
    .string "give you a reward.\p"
    .string "PROF. OAK entrusted me with\n"
    .string "HM05 for you.\p"
    .string "So, {PLAYER}, let me ask you.\p"
    .string "Have you gathered data on at least\n"
    .string "ten kinds of POKéMON?$"

Route2_EastBuilding_Text_GreatHereYouGo::
    .string "Great! You have caught or owned\n"
    .string "{STR_VAR_3} kinds of POKéMON!\p"
    .string "Congratulations!\n"
    .string "Here you go!$"

Route2_EastBuilding_Text_ReceivedHM05FromAide::
    .string "{PLAYER} received HM05\n"
    .string "from the AIDE.$"

Route2_EastBuilding_Text_AlsoTakeRingLight::
    .string "PROF. OAK also wanted you to have\n"
    .string "this RING LIGHT.$"

Route2_EastBuilding_Text_ReceivedRingLightFromAide::
    .string "{PLAYER} received the RING LIGHT\n"
    .string "from the AIDE.$"

Route2_EastBuilding_Text_ExplainHM05::
    .string "With the BOULDER BADGE, use the\n"
    .string "RING LIGHT from your BAG.\p"
    .string "It lights up even the darkest\n"
    .string "caves and dungeons.$"

Route2_EastBuilding_Text_CanGetThroughRockTunnel::
    .string "Once a POKéMON learns FLASH, you\n"
    .string "can get through ROCK TUNNEL.$"

