CeruleanCity_PokemonCenter_1F_Text_BillDoesWhateverForRareMons::
    .string "That BILL!\p"
    .string "I heard that he'll do whatever it\n"
    .string "takes to get rare POKéMON.\p"
    .string "He's not above doing all sorts\n"
    .string "of things, I've heard.$"

CeruleanCity_PokemonCenter_1F_Text_MonsKeepGettingSick::
    .string "My POKéMON keep getting sick.\n"
    .string "Odd little fever every time…\p"
    .string "But then they train harder.\n"
    .string "Twice the gains, I swear!$"

CeruleanCity_PokemonCenter_1F_Text_GaveYourLeadPokerus::
    .string "Hmm… yours looks peaky too.\n"
    .string "There! Caught the same bug.\p"
    .string "They call it POKéRUS.\n"
    .string "Sick now, stronger later!$"

CeruleanCity_PokemonCenter_1F_Text_BillCollectsRareMons::
    .string "BILL has lots of POKéMON!\n"
    .string "He collects rare ones, too!$"

CeruleanCity_PokemonCenter_1F_Text_LoveShinyHunting::
    .string "I love shiny hunting!\n"
    .string "Different colors, same species.\p"
    .string "PROF. OAK gave me a bunch of\n"
    .string "SHINY CHARMS for helping out.\p"
    .string "Take one! It helps you find\n"
    .string "those sparkly POKéMON!$"

CeruleanCity_PokemonCenter_1F_Text_ReceivedShinyCharm::
    .string "{PLAYER} received the\n"
    .string "SHINY CHARM!$"

CeruleanCity_PokemonCenter_1F_Text_KeepHuntingShinies::
    .string "Keep that SHINY CHARM close.\n"
    .string "Oak sent me plenty of extras!$"
