VermilionCity_PokemonCenter_1F_Text_TrainerMonsStrongerThanWild::
    .string "Even if they are the same level,\n"
    .string "POKéMON can have very different\l"
    .string "stats and abilities.\p"
    .string "A POKéMON raised by a TRAINER is\n"
    .string "stronger than one in the wild.$"

VermilionCity_PokemonCenter_1F_Text_PoisonedMonFaintedWhileWalking::
    .string "My POKéMON was poisoned!\n"
    .string "It fainted while we were walking!$"

VermilionCity_PokemonCenter_1F_Text_AllMonWeakToSpecificTypes::
    .string "It is true that a higher-level\n"
    .string "POKéMON will be more powerful…\p"
    .string "But, all POKéMON will have weak\n"
    .string "points against specific types.\p"
    .string "So, there appears to be no\n"
    .string "universally strong POKéMON.$"

VermilionCity_PokemonCenter_1F_Text_UrgeToBattleSomeoneAgain::
    .string "Ever want to battle someone\n"
    .string "again after you've beaten them?\p"
    .string "I've been giving these away.\n"
    .string "Please, take one!$"

VermilionCity_PokemonCenter_1F_Text_UseDeviceForRematches::
    .string "Use the VS SEEKER anywhere.\n"
    .string "No charging needed!\p"
    .string "Nearby TRAINERS will always be\n"
    .string "up for a rematch.\p"
    .string "Their teams get stronger each\n"
    .string "time, right from the start.\p"
    .string "Rematches stick around until\n"
    .string "you leave the area or battle.$"

VermilionCity_PokemonCenter_1F_Text_ExplainVSSeeker::
    .string "Use the VS SEEKER anywhere.\n"
    .string "No charging needed!\p"
    .string "Nearby TRAINERS will always be\n"
    .string "up for a rematch.\p"
    .string "Their teams get stronger each\n"
    .string "time, right from the start.\p"
    .string "Rematches stick around until\n"
    .string "you leave the area or battle.$"
