// Auto-generated by tools/gen_rh_debug_events.py — do not edit by hand.
// Included only from rh_debug_menu.c.

struct RhDebugEvent
{
    u16 flag;
    const u8 *name;
    const u8 *desc;
};

#define EVENT_SUB_NONE 0xFF

enum
{
    EVENT_FOLDER_EARLY,
    EVENT_FOLDER_KANTO,
    EVENT_FOLDER_BADGES,
    EVENT_FOLDER_HMS,
    EVENT_FOLDER_SIDE,
    EVENT_FOLDER_LEGENDS,
    EVENT_FOLDER_SEVII,
    EVENT_FOLDER_WORLDMAP,
    EVENT_FOLDER_SYSMISC,
};

enum
{
    EVENT_KANTO_MTMOON,
    EVENT_KANTO_NUGGET,
    EVENT_KANTO_BILL,
    EVENT_KANTO_CERULEAN,
    EVENT_KANTO_ANNE,
    EVENT_KANTO_ROCKETS,
    EVENT_KANTO_FUJI,
    EVENT_KANTO_SNORLAX,
    EVENT_KANTO_SILPH,
    EVENT_KANTO_PLANT,
    EVENT_KANTO_SEAFOAM,
    EVENT_KANTO_CINNABAR,
    EVENT_KANTO_VIRIDIAN,
    EVENT_KANTO_VR,
    EVENT_KANTO_MISCROCKET,
};

enum
{
    EVENT_SIDE_TRADES,
    EVENT_SIDE_TUTORS,
    EVENT_SIDE_GYMTMS,
    EVENT_SIDE_AIDES,
    EVENT_SIDE_FANCLUB,
    EVENT_SIDE_DAYCARE,
    EVENT_SIDE_MISC,
};

enum
{
    EVENT_SEVII_SYS,
    EVENT_SEVII_TICKETS,
    EVENT_SEVII_CELIO,
    EVENT_SEVII_LOSTELLE,
    EVENT_SEVII_ROCKETS,
    EVENT_SEVII_SELPHY,
    EVENT_SEVII_RUIN,
    EVENT_SEVII_RIVALS,
    EVENT_SEVII_MISC,
};

enum
{
    EVENT_MAP_TOWNS,
    EVENT_MAP_DUNG,
    EVENT_MAP_SEVII,
};

static const u8 sEvtDesc_badge[] = _("Gym badge");
static const u8 sEvtDesc_defeat[] = _("Defeated");
static const u8 sEvtDesc_hide[] = _("Hide object");
static const u8 sEvtDesc_got[] = _("Got item");
static const u8 sEvtDesc_sys[] = _("System flag");
static const u8 sEvtDesc_fought[] = _("Fought");
static const u8 sEvtDesc_flew[] = _("Flew away");
static const u8 sEvtDesc_door[] = _("Door unlocked");
static const u8 sEvtDesc_boulder[] = _("Boulder hide");
static const u8 sEvtDesc_current[] = _("Current stopped");
static const u8 sEvtDesc_map[] = _("Map unlock");
static const u8 sEvtDesc_tutor[] = _("Move tutor");
static const u8 sEvtDesc_trade[] = _("In-game trade");
static const u8 sEvtDesc_quiz[] = _("Gym quiz");
static const u8 sEvtDesc_shop[] = _("Shop progress");

static const u8 sEvtName_SYS_POKEMON_GET[] = _("HAS POKEMON");
static const u8 sEvtName_SYS_POKEDEX_GET[] = _("HAS POKEDEX");
static const u8 sEvtName_SYS_B_DASH[] = _("B DASH");
static const u8 sEvtName_HIDE_BULBASAUR_BALL[] = _("HIDE BULBASAUR BALL");
static const u8 sEvtName_HIDE_SQUIRTLE_BALL[] = _("HIDE SQUIRTLE BALL");
static const u8 sEvtName_HIDE_CHARMANDER_BALL[] = _("HIDE CHARMANDER BALL");
static const u8 sEvtName_HIDE_OAK_IN_HIS_LAB[] = _("HIDE OAK IN LAB");
static const u8 sEvtName_HIDE_OAK_IN_PALLET_TOWN[] = _("HIDE OAK IN PALLET");
static const u8 sEvtName_HIDE_RIVAL_IN_LAB[] = _("HIDE RIVAL IN LAB");
static const u8 sEvtName_HIDE_POKEDEX[] = _("HIDE POKEDEX");
static const u8 sEvtName_HIDE_TOWN_MAP[] = _("HIDE TOWN MAP");
static const u8 sEvtName_VISITED_OAKS_LAB[] = _("VISITED OAKS LAB");
static const u8 sEvtName_BEAT_RIVAL_IN_OAKS_LAB[] = _("BEAT RIVAL IN LAB");
static const u8 sEvtName_GOT_POKEBALLS_FROM_OAK_AFTER_22_RIVAL[] = _("GOT BALLS AFTER 22");
static const u8 sEvtName_OAK_SKIP_22_RIVAL_CHECK[] = _("OAK SKIP 22 CHECK");
static const u8 sEvtName_PALLET_LADY_NOT_BLOCKING_SIGN[] = _("PALLET LADY MOVED");
static const u8 sEvtName_HIDE_VIRIDIAN_CITY_TUTORIAL_MAN[] = _("HIDE VIRIDIAN BLOCK");
static const u8 sEvtName_HIDE_ROUTE_22_RIVAL[] = _("HIDE ROUTE 22 RIVAL");
static const u8 sEvtName_HIDE_PEWTER_CITY_GYM_GUIDE[] = _("HIDE PEWTER GYM GUIDE");
static const u8 sEvtName_HIDE_PEWTER_MUSEUM_GUIDE[] = _("HIDE PEWTER MUSEUM");
static const u8 sEvtName_HIDE_PEWTER_CITY_RUNNING_SHOES_GUY[] = _("HIDE RUNNING SHOES");
static const u8 sEvtName_GOT_POTION_ON_ROUTE_1[] = _("GOT ROUTE 1 POTION");
static const u8 sEvtName_BADGE01_GET[] = _("BADGE 1 BROCK");
static const u8 sEvtName_BADGE02_GET[] = _("BADGE 2 MISTY");
static const u8 sEvtName_BADGE03_GET[] = _("BADGE 3 SURGE");
static const u8 sEvtName_BADGE04_GET[] = _("BADGE 4 ERIKA");
static const u8 sEvtName_BADGE05_GET[] = _("BADGE 5 KOGA");
static const u8 sEvtName_BADGE06_GET[] = _("BADGE 6 SABRINA");
static const u8 sEvtName_BADGE07_GET[] = _("BADGE 7 BLAINE");
static const u8 sEvtName_BADGE08_GET[] = _("BADGE 8 GIOVANNI");
static const u8 sEvtName_DEFEATED_BROCK[] = _("DEFEATED BROCK");
static const u8 sEvtName_DEFEATED_MISTY[] = _("DEFEATED MISTY");
static const u8 sEvtName_DEFEATED_LT_SURGE[] = _("DEFEATED LT SURGE");
static const u8 sEvtName_DEFEATED_ERIKA[] = _("DEFEATED ERIKA");
static const u8 sEvtName_DEFEATED_KOGA[] = _("DEFEATED KOGA");
static const u8 sEvtName_DEFEATED_SABRINA[] = _("DEFEATED SABRINA");
static const u8 sEvtName_DEFEATED_BLAINE[] = _("DEFEATED BLAINE");
static const u8 sEvtName_DEFEATED_LEADER_GIOVANNI[] = _("DEFEATED GIOVANNI");
static const u8 sEvtName_DEFEATED_LORELEI[] = _("DEFEATED LORELEI");
static const u8 sEvtName_DEFEATED_BRUNO[] = _("DEFEATED BRUNO");
static const u8 sEvtName_DEFEATED_AGATHA[] = _("DEFEATED AGATHA");
static const u8 sEvtName_DEFEATED_LANCE[] = _("DEFEATED LANCE");
static const u8 sEvtName_DEFEATED_CHAMP[] = _("DEFEATED CHAMP");
static const u8 sEvtName_SYS_GAME_CLEAR[] = _("GAME CLEAR");
static const u8 sEvtName_HIDE_OAK_IN_CHAMP_ROOM[] = _("HIDE OAK CHAMP ROOM");
static const u8 sEvtName_HIDE_POSTGAME_GOSSIPERS[] = _("HIDE POSTGAME GOSSIP");
static const u8 sEvtName_HIDE_CERULEAN_CAVE_GUARD[] = _("HIDE CERULEAN CAVE");
static const u8 sEvtName_GOT_HM01[] = _("GOT HM01 CUT");
static const u8 sEvtName_GOT_HM02[] = _("GOT HM02 FLY");
static const u8 sEvtName_GOT_HM03[] = _("GOT HM03 SURF");
static const u8 sEvtName_GOT_HM04[] = _("GOT HM04 STRENGTH");
static const u8 sEvtName_GOT_HM05[] = _("GOT HM05 FLASH");
static const u8 sEvtName_GOT_HM06[] = _("GOT HM06 ROCK SMASH");
static const u8 sEvtName_GOT_BIKE_VOUCHER[] = _("GOT BIKE VOUCHER");
static const u8 sEvtName_GOT_BICYCLE[] = _("GOT BICYCLE");
static const u8 sEvtName_GOT_OLD_ROD[] = _("GOT OLD ROD");
static const u8 sEvtName_GOT_GOOD_ROD[] = _("GOT GOOD ROD");
static const u8 sEvtName_GOT_SUPER_ROD[] = _("GOT SUPER ROD");
static const u8 sEvtName_GOT_ITEMFINDER[] = _("GOT ITEMFINDER");
static const u8 sEvtName_GOT_COIN_CASE[] = _("GOT COIN CASE");
static const u8 sEvtName_GOT_VS_SEEKER[] = _("GOT VS SEEKER");
static const u8 sEvtName_GOT_FAME_CHECKER[] = _("GOT FAME CHECKER");
static const u8 sEvtName_GOT_POWDER_JAR[] = _("GOT POWDER JAR");
static const u8 sEvtName_SYS_GOT_BERRY_POUCH[] = _("GOT BERRY POUCH");
static const u8 sEvtName_GOT_EEVEE[] = _("GOT EEVEE");
static const u8 sEvtName_HIDE_EEVEE_BALL[] = _("HIDE EEVEE BALL");
static const u8 sEvtName_GOT_HITMON_FROM_DOJO[] = _("GOT HITMON FROM DOJO");
static const u8 sEvtName_HIDE_DOJO_HITMONLEE_BALL[] = _("HIDE HITMONLEE BALL");
static const u8 sEvtName_HIDE_DOJO_HITMONCHAN_BALL[] = _("HIDE HITMONCHAN BALL");
static const u8 sEvtName_BOUGHT_MAGIKARP[] = _("BOUGHT MAGIKARP");
static const u8 sEvtName_GOT_RECORD_SETTING_MAGIKARP[] = _("GOT RECORD MAGIKARP");
static const u8 sEvtName_GOT_POKE_FLUTE[] = _("GOT POKE FLUTE");
static const u8 sEvtName_GOT_TEA[] = _("GOT TEA");
static const u8 sEvtName_HIDE_ARTICUNO[] = _("HIDE ARTICUNO");
static const u8 sEvtName_FOUGHT_ARTICUNO[] = _("FOUGHT ARTICUNO");
static const u8 sEvtName_HIDE_ZAPDOS[] = _("HIDE ZAPDOS");
static const u8 sEvtName_FOUGHT_ZAPDOS[] = _("FOUGHT ZAPDOS");
static const u8 sEvtName_HIDE_MOLTRES[] = _("HIDE MOLTRES");
static const u8 sEvtName_FOUGHT_MOLTRES[] = _("FOUGHT MOLTRES");
static const u8 sEvtName_HIDE_MEWTWO[] = _("HIDE MEWTWO");
static const u8 sEvtName_FOUGHT_MEWTWO[] = _("FOUGHT MEWTWO");
static const u8 sEvtName_HIDE_LUGIA[] = _("HIDE LUGIA");
static const u8 sEvtName_FOUGHT_LUGIA[] = _("FOUGHT LUGIA");
static const u8 sEvtName_LUGIA_FLEW_AWAY[] = _("LUGIA FLEW AWAY");
static const u8 sEvtName_HIDE_HO_OH[] = _("HIDE HO-OH");
static const u8 sEvtName_FOUGHT_HO_OH[] = _("FOUGHT HO-OH");
static const u8 sEvtName_HO_OH_FLEW_AWAY[] = _("HO-OH FLEW AWAY");
static const u8 sEvtName_HIDE_DEOXYS[] = _("HIDE DEOXYS");
static const u8 sEvtName_FOUGHT_DEOXYS[] = _("FOUGHT DEOXYS");
static const u8 sEvtName_DEOXYS_FLEW_AWAY[] = _("DEOXYS FLEW AWAY");
static const u8 sEvtName_HIDE_BIRTH_ISLAND_METEORITE[] = _("HIDE METEORITE");
static const u8 sEvtName_SYS_DEOXYS_AWAKENED[] = _("DEOXYS AWAKENED");
static const u8 sEvtName_SYS_NOT_SOMEONES_PC[] = _("NOT SOMEONES PC");
static const u8 sEvtName_SYS_RIBBON_GET[] = _("GOT RIBBON");
static const u8 sEvtName_SYS_SAW_HELP_SYSTEM_INTRO[] = _("HELP INTRO SEEN");
static const u8 sEvtName_OPENED_START_MENU[] = _("OPENED START MENU");
static const u8 sEvtName_SYS_SET_TRAINER_CARD_PROFILE[] = _("TRAINER CARD PROFILE");
static const u8 sEvtName_SYS_MYSTERY_GIFT_ENABLED[] = _("MYSTERY GIFT ON");
static const u8 sEvtName_SYS_NUZLOCKE[] = _("NUZLOCKE");
static const u8 sEvtName_SYS_ALL_EXP_SHARE[] = _("ALL EXP SHARE");
static const u8 sEvtName_SYS_SHINY_CHARM[] = _("SHINY CHARM SYS");
static const u8 sEvtName_HIDE_DOME_FOSSIL[] = _("HIDE DOME FOSSIL");
static const u8 sEvtName_HIDE_HELIX_FOSSIL[] = _("HIDE HELIX FOSSIL");
static const u8 sEvtName_GOT_FOSSIL_FROM_MT_MOON[] = _("GOT FOSSIL MT MOON");
static const u8 sEvtName_GOT_DOME_FOSSIL[] = _("GOT DOME FOSSIL");
static const u8 sEvtName_GOT_HELIX_FOSSIL[] = _("GOT HELIX FOSSIL");
static const u8 sEvtName_HIDE_OLD_AMBER[] = _("HIDE OLD AMBER");
static const u8 sEvtName_GOT_OLD_AMBER[] = _("GOT OLD AMBER");
static const u8 sEvtName_REVIVED_DOME[] = _("REVIVED DOME");
static const u8 sEvtName_REVIVED_HELIX[] = _("REVIVED HELIX");
static const u8 sEvtName_REVIVED_AMBER[] = _("REVIVED AMBER");
static const u8 sEvtName_HIDE_NUGGET_BRIDGE_ROCKET[] = _("HIDE NUGGET ROCKET");
static const u8 sEvtName_GOT_TM28_FROM_ROCKET[] = _("GOT TM28 FROM ROCKET");
static const u8 sEvtName_HIDE_BILL_CLEFAIRY[] = _("HIDE BILL CLEFAIRY");
static const u8 sEvtName_HIDE_BILL_HUMAN_SEA_COTTAGE[] = _("HIDE BILL HUMAN");
static const u8 sEvtName_HELPED_BILL_IN_SEA_COTTAGE[] = _("HELPED BILL");
static const u8 sEvtName_HIDE_CERULEAN_ROCKET[] = _("HIDE CERULEAN ROCKET");
static const u8 sEvtName_HIDE_CERULEAN_RIVAL[] = _("HIDE CERULEAN RIVAL");
static const u8 sEvtName_HIDE_SS_ANNE_RIVAL[] = _("HIDE SS ANNE RIVAL");
static const u8 sEvtName_HIDE_SS_ANNE[] = _("HIDE SS ANNE");
static const u8 sEvtName_GOT_SS_TICKET[] = _("GOT SS TICKET");
static const u8 sEvtName_FOUND_BOTH_VERMILION_GYM_SWITCHES[] = _("VERMILION SWITCHES");
static const u8 sEvtName_HIDE_GAME_CORNER_ROCKET[] = _("HIDE GAME CORNER");
static const u8 sEvtName_HIDE_CELADON_ROCKETS[] = _("HIDE CELADON ROCKETS");
static const u8 sEvtName_HIDE_LIFT_KEY[] = _("HIDE LIFT KEY");
static const u8 sEvtName_HIDE_SILPH_SCOPE[] = _("HIDE SILPH SCOPE");
static const u8 sEvtName_HIDE_HIDEOUT_GIOVANNI[] = _("HIDE HIDEOUT GIOVANNI");
static const u8 sEvtName_OPENED_ROCKET_HIDEOUT[] = _("OPENED ROCKET HIDEOUT");
static const u8 sEvtName_CAN_USE_ROCKET_HIDEOUT_LIFT[] = _("ROCKET LIFT WORKS");
static const u8 sEvtName_HIDE_TOWER_ROCKET_1[] = _("HIDE TOWER ROCKET 1");
static const u8 sEvtName_HIDE_TOWER_ROCKET_2[] = _("HIDE TOWER ROCKET 2");
static const u8 sEvtName_HIDE_TOWER_ROCKET_3[] = _("HIDE TOWER ROCKET 3");
static const u8 sEvtName_GOT_10_COINS_FROM_GAMBLER[] = _("GOT 10 COINS");
static const u8 sEvtName_GOT_20_COINS_FROM_GAMBLER[] = _("GOT 20 COINS");
static const u8 sEvtName_GOT_20_COINS_FROM_GAMBLER_2[] = _("GOT 20 COINS 2");
static const u8 sEvtName_HIDE_TOWER_FUJI[] = _("HIDE TOWER FUJI");
static const u8 sEvtName_HIDE_POKEHOUSE_FUJI[] = _("HIDE POKEHOUSE FUJI");
static const u8 sEvtName_HIDE_TOWER_RIVAL[] = _("HIDE TOWER RIVAL");
static const u8 sEvtName_RESCUED_MR_FUJI[] = _("RESCUED MR FUJI");
static const u8 sEvtName_HIDE_ROUTE_12_SNORLAX[] = _("HIDE R12 SNORLAX");
static const u8 sEvtName_WOKE_UP_ROUTE_12_SNORLAX[] = _("WOKE R12 SNORLAX");
static const u8 sEvtName_HIDE_ROUTE_16_SNORLAX[] = _("HIDE R16 SNORLAX");
static const u8 sEvtName_HIDE_SAFFRON_ROCKETS[] = _("HIDE SAFFRON ROCKETS");
static const u8 sEvtName_HIDE_SAFFRON_CIVILIANS[] = _("HIDE SAFFRON CIVILIANS");
static const u8 sEvtName_HIDE_SILPH_ROCKETS[] = _("HIDE SILPH ROCKETS");
static const u8 sEvtName_HIDE_SILPH_RIVAL[] = _("HIDE SILPH RIVAL");
static const u8 sEvtName_GOT_LAPRAS_FROM_SILPH[] = _("GOT LAPRAS");
static const u8 sEvtName_GOT_MASTER_BALL_FROM_SILPH[] = _("GOT MASTER BALL");
static const u8 sEvtName_SILPH_2F_DOOR_1[] = _("SILPH 2F DOOR 1");
static const u8 sEvtName_SILPH_2F_DOOR_2[] = _("SILPH 2F DOOR 2");
static const u8 sEvtName_SILPH_3F_DOOR_1[] = _("SILPH 3F DOOR 1");
static const u8 sEvtName_SILPH_3F_DOOR_2[] = _("SILPH 3F DOOR 2");
static const u8 sEvtName_SILPH_4F_DOOR_1[] = _("SILPH 4F DOOR 1");
static const u8 sEvtName_SILPH_4F_DOOR_2[] = _("SILPH 4F DOOR 2");
static const u8 sEvtName_SILPH_5F_DOOR_1[] = _("SILPH 5F DOOR 1");
static const u8 sEvtName_SILPH_5F_DOOR_2[] = _("SILPH 5F DOOR 2");
static const u8 sEvtName_SILPH_5F_DOOR_3[] = _("SILPH 5F DOOR 3");
static const u8 sEvtName_SILPH_6F_DOOR[] = _("SILPH 6F DOOR");
static const u8 sEvtName_SILPH_7F_DOOR_1[] = _("SILPH 7F DOOR 1");
static const u8 sEvtName_SILPH_7F_DOOR_2[] = _("SILPH 7F DOOR 2");
static const u8 sEvtName_SILPH_7F_DOOR_3[] = _("SILPH 7F DOOR 3");
static const u8 sEvtName_SILPH_8F_DOOR[] = _("SILPH 8F DOOR");
static const u8 sEvtName_SILPH_9F_DOOR_1[] = _("SILPH 9F DOOR 1");
static const u8 sEvtName_SILPH_9F_DOOR_2[] = _("SILPH 9F DOOR 2");
static const u8 sEvtName_SILPH_9F_DOOR_3[] = _("SILPH 9F DOOR 3");
static const u8 sEvtName_SILPH_9F_DOOR_4[] = _("SILPH 9F DOOR 4");
static const u8 sEvtName_SILPH_10F_DOOR[] = _("SILPH 10F DOOR");
static const u8 sEvtName_SILPH_11F_DOOR[] = _("SILPH 11F DOOR");
static const u8 sEvtName_HIDE_POWER_PLANT_ELECTRODE_1[] = _("HIDE ELECTRODE 1");
static const u8 sEvtName_HIDE_POWER_PLANT_ELECTRODE_2[] = _("HIDE ELECTRODE 2");
static const u8 sEvtName_FOUGHT_POWER_PLANT_ELECTRODE_1[] = _("FOUGHT ELECTRODE 1");
static const u8 sEvtName_FOUGHT_POWER_PLANT_ELECTRODE_2[] = _("FOUGHT ELECTRODE 2");
static const u8 sEvtName_HIDE_SEAFOAM_1F_BOULDER_1[] = _("SEAFOAM 1F B1");
static const u8 sEvtName_HIDE_SEAFOAM_1F_BOULDER_2[] = _("SEAFOAM 1F B2");
static const u8 sEvtName_HIDE_SEAFOAM_B1F_BOULDER_1[] = _("SEAFOAM B1F B1");
static const u8 sEvtName_HIDE_SEAFOAM_B1F_BOULDER_2[] = _("SEAFOAM B1F B2");
static const u8 sEvtName_HIDE_SEAFOAM_B2F_BOULDER_1[] = _("SEAFOAM B2F B1");
static const u8 sEvtName_HIDE_SEAFOAM_B2F_BOULDER_2[] = _("SEAFOAM B2F B2");
static const u8 sEvtName_HIDE_SEAFOAM_B3F_BOULDER_1[] = _("SEAFOAM B3F B1");
static const u8 sEvtName_HIDE_SEAFOAM_B3F_BOULDER_2[] = _("SEAFOAM B3F B2");
static const u8 sEvtName_HIDE_SEAFOAM_B3F_BOULDER_3[] = _("SEAFOAM B3F B3");
static const u8 sEvtName_HIDE_SEAFOAM_B3F_BOULDER_4[] = _("SEAFOAM B3F B4");
static const u8 sEvtName_HIDE_SEAFOAM_B3F_BOULDER_5[] = _("SEAFOAM B3F B5");
static const u8 sEvtName_HIDE_SEAFOAM_B3F_BOULDER_6[] = _("SEAFOAM B3F B6");
static const u8 sEvtName_HIDE_SEAFOAM_B4F_BOULDER_1[] = _("SEAFOAM B4F B1");
static const u8 sEvtName_HIDE_SEAFOAM_B4F_BOULDER_2[] = _("SEAFOAM B4F B2");
static const u8 sEvtName_STOPPED_SEAFOAM_B3F_CURRENT[] = _("SEAFOAM B3F CURRENT");
static const u8 sEvtName_STOPPED_SEAFOAM_B4F_CURRENT[] = _("SEAFOAM B4F CURRENT");
static const u8 sEvtName_HIDE_CINNABAR_BILL[] = _("HIDE CINNABAR BILL");
static const u8 sEvtName_HIDE_CINNABAR_SEAGALLOP[] = _("HIDE CINNABAR BOAT");
static const u8 sEvtName_HIDE_CINNABAR_POKECENTER_BILL[] = _("HIDE CINNABAR PC BILL");
static const u8 sEvtName_POKEMON_MANSION_SWITCH_STATE[] = _("MANSION SWITCH");
static const u8 sEvtName_CINNABAR_GYM_QUIZ_1[] = _("CINNABAR QUIZ 1");
static const u8 sEvtName_CINNABAR_GYM_QUIZ_2[] = _("CINNABAR QUIZ 2");
static const u8 sEvtName_CINNABAR_GYM_QUIZ_3[] = _("CINNABAR QUIZ 3");
static const u8 sEvtName_CINNABAR_GYM_QUIZ_4[] = _("CINNABAR QUIZ 4");
static const u8 sEvtName_CINNABAR_GYM_QUIZ_5[] = _("CINNABAR QUIZ 5");
static const u8 sEvtName_CINNABAR_GYM_QUIZ_6[] = _("CINNABAR QUIZ 6");
static const u8 sEvtName_HIDE_VIRIDIAN_GIOVANNI[] = _("HIDE VIRIDIAN GIOVANNI");
static const u8 sEvtName_HIDE_VICTORY_ROAD_2F_BOULDER[] = _("VR 2F BOULDER");
static const u8 sEvtName_HIDE_VICTORY_ROAD_3F_BOULDER[] = _("VR 3F BOULDER");
static const u8 sEvtName_HIDE_MISC_KANTO_ROCKETS[] = _("HIDE MISC ROCKETS");
static const u8 sEvtName_DID_MIMIEN_TRADE[] = _("TRADE MIMIEN");
static const u8 sEvtName_DID_ZYNX_TRADE[] = _("TRADE ZYNX");
static const u8 sEvtName_DID_MS_NIDO_TRADE[] = _("TRADE MS NIDO");
static const u8 sEvtName_DID_CH_DING_TRADE[] = _("TRADE CH DING");
static const u8 sEvtName_DID_NINA_TRADE[] = _("TRADE NINA");
static const u8 sEvtName_DID_MARC_TRADE[] = _("TRADE MARC");
static const u8 sEvtName_DID_ESPHERE_TRADE[] = _("TRADE ESPHERE");
static const u8 sEvtName_DID_TANGENY_TRADE[] = _("TRADE TANGENY");
static const u8 sEvtName_DID_SEELOR_TRADE[] = _("TRADE SEELOR");
static const u8 sEvtName_TUTOR_DOUBLE_EDGE[] = _("TUTOR DOUBLE EDGE");
static const u8 sEvtName_TUTOR_THUNDER_WAVE[] = _("TUTOR THUNDER WAVE");
static const u8 sEvtName_TUTOR_ROCK_SLIDE[] = _("TUTOR ROCK SLIDE");
static const u8 sEvtName_TUTOR_EXPLOSION[] = _("TUTOR EXPLOSION");
static const u8 sEvtName_TUTOR_MEGA_PUNCH[] = _("TUTOR MEGA PUNCH");
static const u8 sEvtName_TUTOR_MEGA_KICK[] = _("TUTOR MEGA KICK");
static const u8 sEvtName_TUTOR_DREAM_EATER[] = _("TUTOR DREAM EATER");
static const u8 sEvtName_TUTOR_SOFT_BOILED[] = _("TUTOR SOFTBOILED");
static const u8 sEvtName_TUTOR_SUBSTITUTE[] = _("TUTOR SUBSTITUTE");
static const u8 sEvtName_TUTOR_SWORDS_DANCE[] = _("TUTOR SWORDS DANCE");
static const u8 sEvtName_TUTOR_SEISMIC_TOSS[] = _("TUTOR SEISMIC TOSS");
static const u8 sEvtName_TUTOR_COUNTER[] = _("TUTOR COUNTER");
static const u8 sEvtName_TUTOR_METRONOME[] = _("TUTOR METRONOME");
static const u8 sEvtName_TUTOR_MIMIC[] = _("TUTOR MIMIC");
static const u8 sEvtName_TUTOR_BODY_SLAM[] = _("TUTOR BODY SLAM");
static const u8 sEvtName_TUTOR_FRENZY_PLANT[] = _("TUTOR FRENZY PLANT");
static const u8 sEvtName_TUTOR_BLAST_BURN[] = _("TUTOR BLAST BURN");
static const u8 sEvtName_TUTOR_HYDRO_CANNON[] = _("TUTOR HYDRO CANNON");
static const u8 sEvtName_LEARNED_ALL_MOVES_AT_CAPE_BRINK[] = _("CAPE BRINK ALL");
static const u8 sEvtName_GOT_TM39_FROM_BROCK[] = _("GOT TM39 BROCK");
static const u8 sEvtName_GOT_TM03_FROM_MISTY[] = _("GOT TM03 MISTY");
static const u8 sEvtName_GOT_TM34_FROM_SURGE[] = _("GOT TM34 SURGE");
static const u8 sEvtName_GOT_TM19_FROM_ERIKA[] = _("GOT TM19 ERIKA");
static const u8 sEvtName_GOT_TM06_FROM_KOGA[] = _("GOT TM06 KOGA");
static const u8 sEvtName_GOT_TM04_FROM_SABRINA[] = _("GOT TM04 SABRINA");
static const u8 sEvtName_GOT_TM38_FROM_BLAINE[] = _("GOT TM38 BLAINE");
static const u8 sEvtName_GOT_TM26_FROM_GIOVANNI[] = _("GOT TM26 GIOVANNI");
static const u8 sEvtName_HIDE_VERMILION_CITY_OAKS_AIDE[] = _("HIDE VERMILION AIDE");
static const u8 sEvtName_TALKED_TO_OAKS_AIDE_IN_VERMILION[] = _("TALKED VERMILION AIDE");
static const u8 sEvtName_GOT_EXP_SHARE_FROM_OAKS_AIDE[] = _("GOT EXP SHARE AIDE");
static const u8 sEvtName_GOT_EVERSTONE_FROM_OAKS_AIDE[] = _("GOT EVERSTONE AIDE");
static const u8 sEvtName_GOT_AMULET_COIN_FROM_OAKS_AIDE[] = _("GOT AMULET COIN AIDE");
static const u8 sEvtName_OAK_SAW_DEX_COMPLETION[] = _("OAK SAW DEX DONE");
static const u8 sEvtName_GOT_SHINY_CHARM[] = _("GOT SHINY CHARM");
static const u8 sEvtName_HIDE_SAFFRON_FAN_CLUB_BLACK_BELT[] = _("HIDE FAN BLACK BELT");
static const u8 sEvtName_HIDE_SAFFRON_FAN_CLUB_ROCKER[] = _("HIDE FAN ROCKER");
static const u8 sEvtName_HIDE_SAFFRON_FAN_CLUB_WOMAN[] = _("HIDE FAN WOMAN");
static const u8 sEvtName_HIDE_SAFFRON_FAN_CLUB_BEAUTY[] = _("HIDE FAN BEAUTY");
static const u8 sEvtName_GOT_TITAN[] = _("GOT TITAN");
static const u8 sEvtName_PENDING_DAYCARE_EGG[] = _("PENDING DAYCARE EGG");
static const u8 sEvtName_GOT_TM29_FROM_MR_PSYCHIC[] = _("GOT TM29 PSYCHIC");
static const u8 sEvtName_GOT_TM33_FROM_THIRSTY_GIRL[] = _("GOT TM33 THIRSTY");
static const u8 sEvtName_GOT_TM20_FROM_THIRSTY_GIRL[] = _("GOT TM20 THIRSTY");
static const u8 sEvtName_GOT_TM16_FROM_THIRSTY_GIRL[] = _("GOT TM16 THIRSTY");
static const u8 sEvtName_GOT_TM27[] = _("GOT TM27");
static const u8 sEvtName_TALKED_TO_TEA_LADY_AFTER_HOF[] = _("TEA LADY AFTER HOF");
static const u8 sEvtName_MET_STICKER_MAN[] = _("MET STICKER MAN");
static const u8 sEvtName_LEARNED_YES_NAH_CHANSEY[] = _("YES NAH CHANSEY");
static const u8 sEvtName_SYS_SEVII_MAP_123[] = _("SEVII MAP 123");
static const u8 sEvtName_SYS_SEVII_MAP_4567[] = _("SEVII MAP 4567");
static const u8 sEvtName_SYS_NATIONAL_DEX[] = _("NATIONAL DEX");
static const u8 sEvtName_SYS_CAN_LINK_WITH_RS[] = _("CAN LINK WITH RS");
static const u8 sEvtName_SYS_UNLOCKED_TANOBY_RUINS[] = _("TANOBY RUINS UNLOCK");
static const u8 sEvtName_SEVII_DETOUR_FINISHED[] = _("SEVII DETOUR DONE");
static const u8 sEvtName_RECEIVED_AURORA_TICKET[] = _("GOT AURORA TICKET");
static const u8 sEvtName_SHOWN_AURORA_TICKET[] = _("SHOWN AURORA TICKET");
static const u8 sEvtName_RECEIVED_MYSTIC_TICKET[] = _("GOT MYSTIC TICKET");
static const u8 sEvtName_SHOWN_MYSTIC_TICKET[] = _("SHOWN MYSTIC TICKET");
static const u8 sEvtName_RECEIVED_OLD_SEA_MAP[] = _("GOT OLD SEA MAP");
static const u8 sEvtName_HIDE_MG_DELIVERYMEN[] = _("HIDE MG DELIVERYMEN");
static const u8 sEvtName_HIDE_ONE_ISLAND_BILL[] = _("HIDE 1I BILL");
static const u8 sEvtName_HIDE_ONE_ISLAND_POKECENTER_BILL[] = _("HIDE 1I PC BILL");
static const u8 sEvtName_HIDE_ONE_ISLAND_POKECENTER_CELIO[] = _("HIDE 1I PC CELIO");
static const u8 sEvtName_HIDE_RUBY[] = _("HIDE RUBY");
static const u8 sEvtName_GOT_RUBY[] = _("GOT RUBY");
static const u8 sEvtName_HIDE_SAPPHIRE[] = _("HIDE SAPPHIRE");
static const u8 sEvtName_RECOVERED_SAPPHIRE[] = _("RECOVERED SAPPHIRE");
static const u8 sEvtName_HIDE_MT_EMBER_EXTERIOR_ROCKETS[] = _("HIDE MT EMBER ROCKETS");
static const u8 sEvtName_HIDE_TWO_ISLAND_GAME_CORNER_BIKER[] = _("HIDE 2I CORNER BIKER");
static const u8 sEvtName_HIDE_TWO_ISLAND_GAME_CORNER_LOSTELLE[] = _("HIDE 2I CORNER LOSTELLE");
static const u8 sEvtName_HIDE_LOSTELLE_IN_HER_HOME[] = _("HIDE LOSTELLE HOME");
static const u8 sEvtName_HIDE_LOSTELLE_IN_BERRY_FOREST[] = _("HIDE LOSTELLE FOREST");
static const u8 sEvtName_HIDE_THREE_ISLAND_BIKERS[] = _("HIDE 3I BIKERS");
static const u8 sEvtName_HIDE_THREE_ISLAND_ANTIBIKERS[] = _("HIDE 3I ANTIBIKERS");
static const u8 sEvtName_HIDE_THREE_ISLAND_LONE_BIKER[] = _("HIDE 3I LONE BIKER");
static const u8 sEvtName_HIDE_TWO_ISLAND_WOMAN[] = _("HIDE 2I WOMAN");
static const u8 sEvtName_HIDE_TWO_ISLAND_BEAUTY[] = _("HIDE 2I BEAUTY");
static const u8 sEvtName_HIDE_TWO_ISLAND_POKE_MANIAC[] = _("HIDE 2I MANIAC");
static const u8 sEvtName_RESCUED_LOSTELLE[] = _("RESCUED LOSTELLE");
static const u8 sEvtName_VISITED_TWO_ISLAND[] = _("VISITED TWO ISLAND");
static const u8 sEvtName_GOT_FULL_RESTORE_FROM_THREE_ISLAND_DEFENDER[] = _("GOT 3I FULL RESTORE");
static const u8 sEvtName_HIDE_FIVE_ISLAND_ROCKETS[] = _("HIDE 5I ROCKETS");
static const u8 sEvtName_HIDE_ICEFALL_CAVE_LORELEI[] = _("HIDE ICEFALL LORELEI");
static const u8 sEvtName_HIDE_LORELEI_IN_HER_HOUSE[] = _("HIDE LORELEI HOUSE");
static const u8 sEvtName_HIDE_ICEFALL_CAVE_ROCKETS[] = _("HIDE ICEFALL ROCKETS");
static const u8 sEvtName_DEFEATED_ROCKETS_IN_WAREHOUSE[] = _("DEFEATED WAREHOUSE");
static const u8 sEvtName_UNLOCKED_ROCKET_WAREHOUSE[] = _("UNLOCKED WAREHOUSE");
static const u8 sEvtName_TALKED_TO_LORELEI_AFTER_WAREHOUSE[] = _("LORELEI AFTER WH");
static const u8 sEvtName_HIDE_LOST_CAVE_SELPHY[] = _("HIDE LOST CAVE SELPHY");
static const u8 sEvtName_HIDE_RESORT_GORGEOUS_SELPHY[] = _("HIDE RESORT SELPHY");
static const u8 sEvtName_HIDE_RESORT_GORGEOUS_INSIDE_SELPHY[] = _("HIDE INSIDE SELPHY");
static const u8 sEvtName_HIDE_SELPHYS_BUTLER[] = _("HIDE SELPHY BUTLER");
static const u8 sEvtName_GOT_TOGEPI_EGG[] = _("GOT TOGEPI EGG");
static const u8 sEvtName_HIDE_RUIN_VALLEY_SCIENTIST[] = _("HIDE RUIN SCIENTIST");
static const u8 sEvtName_HIDE_DOTTED_HOLE_SCIENTIST[] = _("HIDE DOTTED SCIENTIST");
static const u8 sEvtName_USED_CUT_ON_RUIN_VALLEY_BRAILLE[] = _("CUT RUIN BRAILLE");
static const u8 sEvtName_HIDE_FOUR_ISLAND_RIVAL[] = _("HIDE 4I RIVAL");
static const u8 sEvtName_HIDE_SIX_ISLAND_POKECENTER_RIVAL[] = _("HIDE 6I PC RIVAL");
static const u8 sEvtName_TWO_ISLAND_SHOP_INTRODUCED[] = _("2I SHOP INTRO");
static const u8 sEvtName_TWO_ISLAND_SHOP_EXPANDED_1[] = _("2I SHOP EXPAND 1");
static const u8 sEvtName_TWO_ISLAND_SHOP_EXPANDED_2[] = _("2I SHOP EXPAND 2");
static const u8 sEvtName_TWO_ISLAND_SHOP_EXPANDED_3[] = _("2I SHOP EXPAND 3");
static const u8 sEvtName_GOT_TM42_AT_MEMORIAL_PILLAR[] = _("GOT TM42 MEMORIAL");
static const u8 sEvtName_GOT_MOON_STONE_FROM_JOYFUL_GAME_CORNER[] = _("GOT JOYFUL MOON STONE");
static const u8 sEvtName_GOT_NEST_BALL_FROM_WATER_PATH_HOUSE_1[] = _("GOT NEST BALL WATER");
static const u8 sEvtName_GOT_NUGGET_FROM_DUNSPARCE_TUNNEL[] = _("GOT DUNSPARCE NUGGET");
static const u8 sEvtName_WORLD_MAP_PALLET_TOWN[] = _("MAP PALLET");
static const u8 sEvtName_WORLD_MAP_VIRIDIAN_CITY[] = _("MAP VIRIDIAN");
static const u8 sEvtName_WORLD_MAP_PEWTER_CITY[] = _("MAP PEWTER");
static const u8 sEvtName_WORLD_MAP_CERULEAN_CITY[] = _("MAP CERULEAN");
static const u8 sEvtName_WORLD_MAP_LAVENDER_TOWN[] = _("MAP LAVENDER");
static const u8 sEvtName_WORLD_MAP_VERMILION_CITY[] = _("MAP VERMILION");
static const u8 sEvtName_WORLD_MAP_CELADON_CITY[] = _("MAP CELADON");
static const u8 sEvtName_WORLD_MAP_FUCHSIA_CITY[] = _("MAP FUCHSIA");
static const u8 sEvtName_WORLD_MAP_CINNABAR_ISLAND[] = _("MAP CINNABAR");
static const u8 sEvtName_WORLD_MAP_INDIGO_PLATEAU_EXTERIOR[] = _("MAP INDIGO");
static const u8 sEvtName_WORLD_MAP_SAFFRON_CITY[] = _("MAP SAFFRON");
static const u8 sEvtName_WORLD_MAP_ROUTE4_POKEMON_CENTER_1F[] = _("MAP ROUTE 4 PC");
static const u8 sEvtName_WORLD_MAP_ROUTE10_POKEMON_CENTER_1F[] = _("MAP ROUTE 10 PC");
static const u8 sEvtName_WORLD_MAP_VIRIDIAN_FOREST[] = _("MAP VIRIDIAN FOREST");
static const u8 sEvtName_WORLD_MAP_MT_MOON_1F[] = _("MAP MT MOON");
static const u8 sEvtName_WORLD_MAP_SSANNE_EXTERIOR[] = _("MAP SS ANNE");
static const u8 sEvtName_WORLD_MAP_UNDERGROUND_PATH_NORTH_SOUTH_TUNNEL[] = _("MAP UG NS");
static const u8 sEvtName_WORLD_MAP_UNDERGROUND_PATH_EAST_WEST_TUNNEL[] = _("MAP UG EW");
static const u8 sEvtName_WORLD_MAP_DIGLETTS_CAVE_B1F[] = _("MAP DIGLETT CAVE");
static const u8 sEvtName_WORLD_MAP_VICTORY_ROAD_1F[] = _("MAP VICTORY ROAD");
static const u8 sEvtName_WORLD_MAP_ROCKET_HIDEOUT_B1F[] = _("MAP ROCKET HIDEOUT");
static const u8 sEvtName_WORLD_MAP_SILPH_CO_1F[] = _("MAP SILPH CO");
static const u8 sEvtName_WORLD_MAP_POKEMON_MANSION_1F[] = _("MAP MANSION");
static const u8 sEvtName_WORLD_MAP_SAFARI_ZONE_CENTER[] = _("MAP SAFARI ZONE");
static const u8 sEvtName_WORLD_MAP_POKEMON_LEAGUE_LORELEIS_ROOM[] = _("MAP LEAGUE");
static const u8 sEvtName_WORLD_MAP_ROCK_TUNNEL_1F[] = _("MAP ROCK TUNNEL");
static const u8 sEvtName_WORLD_MAP_SEAFOAM_ISLANDS_1F[] = _("MAP SEAFOAM");
static const u8 sEvtName_WORLD_MAP_POKEMON_TOWER_1F[] = _("MAP POKE TOWER");
static const u8 sEvtName_WORLD_MAP_CERULEAN_CAVE_1F[] = _("MAP CERULEAN CAVE");
static const u8 sEvtName_WORLD_MAP_POWER_PLANT[] = _("MAP POWER PLANT");
static const u8 sEvtName_WORLD_MAP_ONE_ISLAND[] = _("MAP ONE ISLAND");
static const u8 sEvtName_WORLD_MAP_TWO_ISLAND[] = _("MAP TWO ISLAND");
static const u8 sEvtName_WORLD_MAP_THREE_ISLAND[] = _("MAP THREE ISLAND");
static const u8 sEvtName_WORLD_MAP_FOUR_ISLAND[] = _("MAP FOUR ISLAND");
static const u8 sEvtName_WORLD_MAP_FIVE_ISLAND[] = _("MAP FIVE ISLAND");
static const u8 sEvtName_WORLD_MAP_SIX_ISLAND[] = _("MAP SIX ISLAND");
static const u8 sEvtName_WORLD_MAP_SEVEN_ISLAND[] = _("MAP SEVEN ISLAND");
static const u8 sEvtName_WORLD_MAP_NAVEL_ROCK_EXTERIOR[] = _("MAP NAVEL ROCK");
static const u8 sEvtName_WORLD_MAP_MT_EMBER_EXTERIOR[] = _("MAP MT EMBER");
static const u8 sEvtName_WORLD_MAP_THREE_ISLAND_BERRY_FOREST[] = _("MAP BERRY FOREST");
static const u8 sEvtName_WORLD_MAP_FOUR_ISLAND_ICEFALL_CAVE_ENTRANCE[] = _("MAP ICEFALL CAVE");
static const u8 sEvtName_WORLD_MAP_FIVE_ISLAND_ROCKET_WAREHOUSE[] = _("MAP ROCKET WH");
static const u8 sEvtName_WORLD_MAP_TRAINER_TOWER_LOBBY[] = _("MAP TRAINER TOWER");
static const u8 sEvtName_WORLD_MAP_SIX_ISLAND_DOTTED_HOLE_1F[] = _("MAP DOTTED HOLE");
static const u8 sEvtName_WORLD_MAP_FIVE_ISLAND_LOST_CAVE_ENTRANCE[] = _("MAP LOST CAVE");
static const u8 sEvtName_WORLD_MAP_SIX_ISLAND_PATTERN_BUSH[] = _("MAP PATTERN BUSH");
static const u8 sEvtName_WORLD_MAP_SIX_ISLAND_ALTERING_CAVE[] = _("MAP ALTERING CAVE");
static const u8 sEvtName_WORLD_MAP_SEVEN_ISLAND_TANOBY_RUINS_MONEAN_CHAMBER[] = _("MAP TANOBY");
static const u8 sEvtName_WORLD_MAP_THREE_ISLAND_DUNSPARCE_TUNNEL[] = _("MAP DUNSPARCE");
static const u8 sEvtName_WORLD_MAP_SEVEN_ISLAND_SEVAULT_CANYON_TANOBY_KEY[] = _("MAP TANOBY KEY");
static const u8 sEvtName_WORLD_MAP_BIRTH_ISLAND_EXTERIOR[] = _("MAP BIRTH ISLAND");

static const struct RhDebugEvent sEvents_early[] =
{
    {FLAG_SYS_POKEMON_GET, sEvtName_SYS_POKEMON_GET, sEvtDesc_sys},
    {FLAG_SYS_POKEDEX_GET, sEvtName_SYS_POKEDEX_GET, sEvtDesc_sys},
    {FLAG_SYS_B_DASH, sEvtName_SYS_B_DASH, sEvtDesc_sys},
    {FLAG_HIDE_BULBASAUR_BALL, sEvtName_HIDE_BULBASAUR_BALL, sEvtDesc_hide},
    {FLAG_HIDE_SQUIRTLE_BALL, sEvtName_HIDE_SQUIRTLE_BALL, sEvtDesc_hide},
    {FLAG_HIDE_CHARMANDER_BALL, sEvtName_HIDE_CHARMANDER_BALL, sEvtDesc_hide},
    {FLAG_HIDE_OAK_IN_HIS_LAB, sEvtName_HIDE_OAK_IN_HIS_LAB, sEvtDesc_hide},
    {FLAG_HIDE_OAK_IN_PALLET_TOWN, sEvtName_HIDE_OAK_IN_PALLET_TOWN, sEvtDesc_hide},
    {FLAG_HIDE_RIVAL_IN_LAB, sEvtName_HIDE_RIVAL_IN_LAB, sEvtDesc_hide},
    {FLAG_HIDE_POKEDEX, sEvtName_HIDE_POKEDEX, sEvtDesc_hide},
    {FLAG_HIDE_TOWN_MAP, sEvtName_HIDE_TOWN_MAP, sEvtDesc_hide},
    {FLAG_VISITED_OAKS_LAB, sEvtName_VISITED_OAKS_LAB, sEvtDesc_sys},
    {FLAG_BEAT_RIVAL_IN_OAKS_LAB, sEvtName_BEAT_RIVAL_IN_OAKS_LAB, sEvtDesc_defeat},
    {FLAG_GOT_POKEBALLS_FROM_OAK_AFTER_22_RIVAL, sEvtName_GOT_POKEBALLS_FROM_OAK_AFTER_22_RIVAL, sEvtDesc_got},
    {FLAG_OAK_SKIP_22_RIVAL_CHECK, sEvtName_OAK_SKIP_22_RIVAL_CHECK, sEvtDesc_sys},
    {FLAG_PALLET_LADY_NOT_BLOCKING_SIGN, sEvtName_PALLET_LADY_NOT_BLOCKING_SIGN, sEvtDesc_sys},
    {FLAG_HIDE_VIRIDIAN_CITY_TUTORIAL_MAN, sEvtName_HIDE_VIRIDIAN_CITY_TUTORIAL_MAN, sEvtDesc_hide},
    {FLAG_HIDE_ROUTE_22_RIVAL, sEvtName_HIDE_ROUTE_22_RIVAL, sEvtDesc_hide},
    {FLAG_HIDE_PEWTER_CITY_GYM_GUIDE, sEvtName_HIDE_PEWTER_CITY_GYM_GUIDE, sEvtDesc_hide},
    {FLAG_HIDE_PEWTER_MUSEUM_GUIDE, sEvtName_HIDE_PEWTER_MUSEUM_GUIDE, sEvtDesc_hide},
    {FLAG_HIDE_PEWTER_CITY_RUNNING_SHOES_GUY, sEvtName_HIDE_PEWTER_CITY_RUNNING_SHOES_GUY, sEvtDesc_hide},
    {FLAG_GOT_POTION_ON_ROUTE_1, sEvtName_GOT_POTION_ON_ROUTE_1, sEvtDesc_got},
};

static const struct RhDebugEvent sEvents_badges[] =
{
    {FLAG_BADGE01_GET, sEvtName_BADGE01_GET, sEvtDesc_badge},
    {FLAG_BADGE02_GET, sEvtName_BADGE02_GET, sEvtDesc_badge},
    {FLAG_BADGE03_GET, sEvtName_BADGE03_GET, sEvtDesc_badge},
    {FLAG_BADGE04_GET, sEvtName_BADGE04_GET, sEvtDesc_badge},
    {FLAG_BADGE05_GET, sEvtName_BADGE05_GET, sEvtDesc_badge},
    {FLAG_BADGE06_GET, sEvtName_BADGE06_GET, sEvtDesc_badge},
    {FLAG_BADGE07_GET, sEvtName_BADGE07_GET, sEvtDesc_badge},
    {FLAG_BADGE08_GET, sEvtName_BADGE08_GET, sEvtDesc_badge},
    {FLAG_DEFEATED_BROCK, sEvtName_DEFEATED_BROCK, sEvtDesc_defeat},
    {FLAG_DEFEATED_MISTY, sEvtName_DEFEATED_MISTY, sEvtDesc_defeat},
    {FLAG_DEFEATED_LT_SURGE, sEvtName_DEFEATED_LT_SURGE, sEvtDesc_defeat},
    {FLAG_DEFEATED_ERIKA, sEvtName_DEFEATED_ERIKA, sEvtDesc_defeat},
    {FLAG_DEFEATED_KOGA, sEvtName_DEFEATED_KOGA, sEvtDesc_defeat},
    {FLAG_DEFEATED_SABRINA, sEvtName_DEFEATED_SABRINA, sEvtDesc_defeat},
    {FLAG_DEFEATED_BLAINE, sEvtName_DEFEATED_BLAINE, sEvtDesc_defeat},
    {FLAG_DEFEATED_LEADER_GIOVANNI, sEvtName_DEFEATED_LEADER_GIOVANNI, sEvtDesc_defeat},
    {FLAG_DEFEATED_LORELEI, sEvtName_DEFEATED_LORELEI, sEvtDesc_defeat},
    {FLAG_DEFEATED_BRUNO, sEvtName_DEFEATED_BRUNO, sEvtDesc_defeat},
    {FLAG_DEFEATED_AGATHA, sEvtName_DEFEATED_AGATHA, sEvtDesc_defeat},
    {FLAG_DEFEATED_LANCE, sEvtName_DEFEATED_LANCE, sEvtDesc_defeat},
    {FLAG_DEFEATED_CHAMP, sEvtName_DEFEATED_CHAMP, sEvtDesc_defeat},
    {FLAG_SYS_GAME_CLEAR, sEvtName_SYS_GAME_CLEAR, sEvtDesc_sys},
    {FLAG_HIDE_OAK_IN_CHAMP_ROOM, sEvtName_HIDE_OAK_IN_CHAMP_ROOM, sEvtDesc_hide},
    {FLAG_HIDE_POSTGAME_GOSSIPERS, sEvtName_HIDE_POSTGAME_GOSSIPERS, sEvtDesc_hide},
    {FLAG_HIDE_CERULEAN_CAVE_GUARD, sEvtName_HIDE_CERULEAN_CAVE_GUARD, sEvtDesc_hide},
};

static const struct RhDebugEvent sEvents_hms[] =
{
    {FLAG_GOT_HM01, sEvtName_GOT_HM01, sEvtDesc_got},
    {FLAG_GOT_HM02, sEvtName_GOT_HM02, sEvtDesc_got},
    {FLAG_GOT_HM03, sEvtName_GOT_HM03, sEvtDesc_got},
    {FLAG_GOT_HM04, sEvtName_GOT_HM04, sEvtDesc_got},
    {FLAG_GOT_HM05, sEvtName_GOT_HM05, sEvtDesc_got},
    {FLAG_GOT_HM06, sEvtName_GOT_HM06, sEvtDesc_got},
    {FLAG_GOT_BIKE_VOUCHER, sEvtName_GOT_BIKE_VOUCHER, sEvtDesc_got},
    {FLAG_GOT_BICYCLE, sEvtName_GOT_BICYCLE, sEvtDesc_got},
    {FLAG_GOT_OLD_ROD, sEvtName_GOT_OLD_ROD, sEvtDesc_got},
    {FLAG_GOT_GOOD_ROD, sEvtName_GOT_GOOD_ROD, sEvtDesc_got},
    {FLAG_GOT_SUPER_ROD, sEvtName_GOT_SUPER_ROD, sEvtDesc_got},
    {FLAG_GOT_ITEMFINDER, sEvtName_GOT_ITEMFINDER, sEvtDesc_got},
    {FLAG_GOT_COIN_CASE, sEvtName_GOT_COIN_CASE, sEvtDesc_got},
    {FLAG_GOT_VS_SEEKER, sEvtName_GOT_VS_SEEKER, sEvtDesc_got},
    {FLAG_GOT_FAME_CHECKER, sEvtName_GOT_FAME_CHECKER, sEvtDesc_got},
    {FLAG_GOT_POWDER_JAR, sEvtName_GOT_POWDER_JAR, sEvtDesc_got},
    {FLAG_SYS_GOT_BERRY_POUCH, sEvtName_SYS_GOT_BERRY_POUCH, sEvtDesc_sys},
    {FLAG_GOT_EEVEE, sEvtName_GOT_EEVEE, sEvtDesc_got},
    {FLAG_HIDE_EEVEE_BALL, sEvtName_HIDE_EEVEE_BALL, sEvtDesc_hide},
    {FLAG_GOT_HITMON_FROM_DOJO, sEvtName_GOT_HITMON_FROM_DOJO, sEvtDesc_got},
    {FLAG_HIDE_DOJO_HITMONLEE_BALL, sEvtName_HIDE_DOJO_HITMONLEE_BALL, sEvtDesc_hide},
    {FLAG_HIDE_DOJO_HITMONCHAN_BALL, sEvtName_HIDE_DOJO_HITMONCHAN_BALL, sEvtDesc_hide},
    {FLAG_BOUGHT_MAGIKARP, sEvtName_BOUGHT_MAGIKARP, sEvtDesc_got},
    {FLAG_GOT_RECORD_SETTING_MAGIKARP, sEvtName_GOT_RECORD_SETTING_MAGIKARP, sEvtDesc_got},
    {FLAG_GOT_POKE_FLUTE, sEvtName_GOT_POKE_FLUTE, sEvtDesc_got},
    {FLAG_GOT_TEA, sEvtName_GOT_TEA, sEvtDesc_got},
};

static const struct RhDebugEvent sEvents_legends[] =
{
    {FLAG_HIDE_ARTICUNO, sEvtName_HIDE_ARTICUNO, sEvtDesc_hide},
    {FLAG_FOUGHT_ARTICUNO, sEvtName_FOUGHT_ARTICUNO, sEvtDesc_fought},
    {FLAG_HIDE_ZAPDOS, sEvtName_HIDE_ZAPDOS, sEvtDesc_hide},
    {FLAG_FOUGHT_ZAPDOS, sEvtName_FOUGHT_ZAPDOS, sEvtDesc_fought},
    {FLAG_HIDE_MOLTRES, sEvtName_HIDE_MOLTRES, sEvtDesc_hide},
    {FLAG_FOUGHT_MOLTRES, sEvtName_FOUGHT_MOLTRES, sEvtDesc_fought},
    {FLAG_HIDE_MEWTWO, sEvtName_HIDE_MEWTWO, sEvtDesc_hide},
    {FLAG_FOUGHT_MEWTWO, sEvtName_FOUGHT_MEWTWO, sEvtDesc_fought},
    {FLAG_HIDE_LUGIA, sEvtName_HIDE_LUGIA, sEvtDesc_hide},
    {FLAG_FOUGHT_LUGIA, sEvtName_FOUGHT_LUGIA, sEvtDesc_fought},
    {FLAG_LUGIA_FLEW_AWAY, sEvtName_LUGIA_FLEW_AWAY, sEvtDesc_flew},
    {FLAG_HIDE_HO_OH, sEvtName_HIDE_HO_OH, sEvtDesc_hide},
    {FLAG_FOUGHT_HO_OH, sEvtName_FOUGHT_HO_OH, sEvtDesc_fought},
    {FLAG_HO_OH_FLEW_AWAY, sEvtName_HO_OH_FLEW_AWAY, sEvtDesc_flew},
    {FLAG_HIDE_DEOXYS, sEvtName_HIDE_DEOXYS, sEvtDesc_hide},
    {FLAG_FOUGHT_DEOXYS, sEvtName_FOUGHT_DEOXYS, sEvtDesc_fought},
    {FLAG_DEOXYS_FLEW_AWAY, sEvtName_DEOXYS_FLEW_AWAY, sEvtDesc_flew},
    {FLAG_HIDE_BIRTH_ISLAND_METEORITE, sEvtName_HIDE_BIRTH_ISLAND_METEORITE, sEvtDesc_hide},
    {FLAG_SYS_DEOXYS_AWAKENED, sEvtName_SYS_DEOXYS_AWAKENED, sEvtDesc_sys},
};

static const struct RhDebugEvent sEvents_sysmisc[] =
{
    {FLAG_SYS_NOT_SOMEONES_PC, sEvtName_SYS_NOT_SOMEONES_PC, sEvtDesc_sys},
    {FLAG_SYS_RIBBON_GET, sEvtName_SYS_RIBBON_GET, sEvtDesc_sys},
    {FLAG_SYS_SAW_HELP_SYSTEM_INTRO, sEvtName_SYS_SAW_HELP_SYSTEM_INTRO, sEvtDesc_sys},
    {FLAG_OPENED_START_MENU, sEvtName_OPENED_START_MENU, sEvtDesc_sys},
    {FLAG_SYS_SET_TRAINER_CARD_PROFILE, sEvtName_SYS_SET_TRAINER_CARD_PROFILE, sEvtDesc_sys},
    {FLAG_SYS_MYSTERY_GIFT_ENABLED, sEvtName_SYS_MYSTERY_GIFT_ENABLED, sEvtDesc_sys},
    {FLAG_SYS_NUZLOCKE, sEvtName_SYS_NUZLOCKE, sEvtDesc_sys},
    {FLAG_SYS_ALL_EXP_SHARE, sEvtName_SYS_ALL_EXP_SHARE, sEvtDesc_sys},
    {FLAG_SYS_SHINY_CHARM, sEvtName_SYS_SHINY_CHARM, sEvtDesc_sys},
};

static const struct RhDebugEvent sEvents_k_mtmoon[] =
{
    {FLAG_HIDE_DOME_FOSSIL, sEvtName_HIDE_DOME_FOSSIL, sEvtDesc_hide},
    {FLAG_HIDE_HELIX_FOSSIL, sEvtName_HIDE_HELIX_FOSSIL, sEvtDesc_hide},
    {FLAG_GOT_FOSSIL_FROM_MT_MOON, sEvtName_GOT_FOSSIL_FROM_MT_MOON, sEvtDesc_got},
    {FLAG_GOT_DOME_FOSSIL, sEvtName_GOT_DOME_FOSSIL, sEvtDesc_got},
    {FLAG_GOT_HELIX_FOSSIL, sEvtName_GOT_HELIX_FOSSIL, sEvtDesc_got},
    {FLAG_HIDE_OLD_AMBER, sEvtName_HIDE_OLD_AMBER, sEvtDesc_hide},
    {FLAG_GOT_OLD_AMBER, sEvtName_GOT_OLD_AMBER, sEvtDesc_got},
    {FLAG_REVIVED_DOME, sEvtName_REVIVED_DOME, sEvtDesc_sys},
    {FLAG_REVIVED_HELIX, sEvtName_REVIVED_HELIX, sEvtDesc_sys},
    {FLAG_REVIVED_AMBER, sEvtName_REVIVED_AMBER, sEvtDesc_sys},
};

static const struct RhDebugEvent sEvents_k_nugget[] =
{
    {FLAG_HIDE_NUGGET_BRIDGE_ROCKET, sEvtName_HIDE_NUGGET_BRIDGE_ROCKET, sEvtDesc_hide},
    {FLAG_GOT_TM28_FROM_ROCKET, sEvtName_GOT_TM28_FROM_ROCKET, sEvtDesc_got},
};

static const struct RhDebugEvent sEvents_k_bill[] =
{
    {FLAG_HIDE_BILL_CLEFAIRY, sEvtName_HIDE_BILL_CLEFAIRY, sEvtDesc_hide},
    {FLAG_HIDE_BILL_HUMAN_SEA_COTTAGE, sEvtName_HIDE_BILL_HUMAN_SEA_COTTAGE, sEvtDesc_hide},
    {FLAG_HELPED_BILL_IN_SEA_COTTAGE, sEvtName_HELPED_BILL_IN_SEA_COTTAGE, sEvtDesc_sys},
};

static const struct RhDebugEvent sEvents_k_cerulean[] =
{
    {FLAG_HIDE_CERULEAN_ROCKET, sEvtName_HIDE_CERULEAN_ROCKET, sEvtDesc_hide},
    {FLAG_HIDE_CERULEAN_RIVAL, sEvtName_HIDE_CERULEAN_RIVAL, sEvtDesc_hide},
};

static const struct RhDebugEvent sEvents_k_anne[] =
{
    {FLAG_HIDE_SS_ANNE_RIVAL, sEvtName_HIDE_SS_ANNE_RIVAL, sEvtDesc_hide},
    {FLAG_HIDE_SS_ANNE, sEvtName_HIDE_SS_ANNE, sEvtDesc_hide},
    {FLAG_GOT_SS_TICKET, sEvtName_GOT_SS_TICKET, sEvtDesc_got},
    {FLAG_FOUND_BOTH_VERMILION_GYM_SWITCHES, sEvtName_FOUND_BOTH_VERMILION_GYM_SWITCHES, sEvtDesc_sys},
};

static const struct RhDebugEvent sEvents_k_rockets[] =
{
    {FLAG_HIDE_GAME_CORNER_ROCKET, sEvtName_HIDE_GAME_CORNER_ROCKET, sEvtDesc_hide},
    {FLAG_HIDE_CELADON_ROCKETS, sEvtName_HIDE_CELADON_ROCKETS, sEvtDesc_hide},
    {FLAG_HIDE_LIFT_KEY, sEvtName_HIDE_LIFT_KEY, sEvtDesc_hide},
    {FLAG_HIDE_SILPH_SCOPE, sEvtName_HIDE_SILPH_SCOPE, sEvtDesc_hide},
    {FLAG_HIDE_HIDEOUT_GIOVANNI, sEvtName_HIDE_HIDEOUT_GIOVANNI, sEvtDesc_hide},
    {FLAG_OPENED_ROCKET_HIDEOUT, sEvtName_OPENED_ROCKET_HIDEOUT, sEvtDesc_sys},
    {FLAG_CAN_USE_ROCKET_HIDEOUT_LIFT, sEvtName_CAN_USE_ROCKET_HIDEOUT_LIFT, sEvtDesc_sys},
    {FLAG_HIDE_TOWER_ROCKET_1, sEvtName_HIDE_TOWER_ROCKET_1, sEvtDesc_hide},
    {FLAG_HIDE_TOWER_ROCKET_2, sEvtName_HIDE_TOWER_ROCKET_2, sEvtDesc_hide},
    {FLAG_HIDE_TOWER_ROCKET_3, sEvtName_HIDE_TOWER_ROCKET_3, sEvtDesc_hide},
    {FLAG_GOT_10_COINS_FROM_GAMBLER, sEvtName_GOT_10_COINS_FROM_GAMBLER, sEvtDesc_got},
    {FLAG_GOT_20_COINS_FROM_GAMBLER, sEvtName_GOT_20_COINS_FROM_GAMBLER, sEvtDesc_got},
    {FLAG_GOT_20_COINS_FROM_GAMBLER_2, sEvtName_GOT_20_COINS_FROM_GAMBLER_2, sEvtDesc_got},
};

static const struct RhDebugEvent sEvents_k_fuji[] =
{
    {FLAG_HIDE_TOWER_FUJI, sEvtName_HIDE_TOWER_FUJI, sEvtDesc_hide},
    {FLAG_HIDE_POKEHOUSE_FUJI, sEvtName_HIDE_POKEHOUSE_FUJI, sEvtDesc_hide},
    {FLAG_HIDE_TOWER_RIVAL, sEvtName_HIDE_TOWER_RIVAL, sEvtDesc_hide},
    {FLAG_RESCUED_MR_FUJI, sEvtName_RESCUED_MR_FUJI, sEvtDesc_sys},
};

static const struct RhDebugEvent sEvents_k_snorlax[] =
{
    {FLAG_HIDE_ROUTE_12_SNORLAX, sEvtName_HIDE_ROUTE_12_SNORLAX, sEvtDesc_hide},
    {FLAG_WOKE_UP_ROUTE_12_SNORLAX, sEvtName_WOKE_UP_ROUTE_12_SNORLAX, sEvtDesc_sys},
    {FLAG_HIDE_ROUTE_16_SNORLAX, sEvtName_HIDE_ROUTE_16_SNORLAX, sEvtDesc_hide},
};

static const struct RhDebugEvent sEvents_k_silph[] =
{
    {FLAG_HIDE_SAFFRON_ROCKETS, sEvtName_HIDE_SAFFRON_ROCKETS, sEvtDesc_hide},
    {FLAG_HIDE_SAFFRON_CIVILIANS, sEvtName_HIDE_SAFFRON_CIVILIANS, sEvtDesc_hide},
    {FLAG_HIDE_SILPH_ROCKETS, sEvtName_HIDE_SILPH_ROCKETS, sEvtDesc_hide},
    {FLAG_HIDE_SILPH_RIVAL, sEvtName_HIDE_SILPH_RIVAL, sEvtDesc_hide},
    {FLAG_GOT_LAPRAS_FROM_SILPH, sEvtName_GOT_LAPRAS_FROM_SILPH, sEvtDesc_got},
    {FLAG_GOT_MASTER_BALL_FROM_SILPH, sEvtName_GOT_MASTER_BALL_FROM_SILPH, sEvtDesc_got},
    {FLAG_SILPH_2F_DOOR_1, sEvtName_SILPH_2F_DOOR_1, sEvtDesc_door},
    {FLAG_SILPH_2F_DOOR_2, sEvtName_SILPH_2F_DOOR_2, sEvtDesc_door},
    {FLAG_SILPH_3F_DOOR_1, sEvtName_SILPH_3F_DOOR_1, sEvtDesc_door},
    {FLAG_SILPH_3F_DOOR_2, sEvtName_SILPH_3F_DOOR_2, sEvtDesc_door},
    {FLAG_SILPH_4F_DOOR_1, sEvtName_SILPH_4F_DOOR_1, sEvtDesc_door},
    {FLAG_SILPH_4F_DOOR_2, sEvtName_SILPH_4F_DOOR_2, sEvtDesc_door},
    {FLAG_SILPH_5F_DOOR_1, sEvtName_SILPH_5F_DOOR_1, sEvtDesc_door},
    {FLAG_SILPH_5F_DOOR_2, sEvtName_SILPH_5F_DOOR_2, sEvtDesc_door},
    {FLAG_SILPH_5F_DOOR_3, sEvtName_SILPH_5F_DOOR_3, sEvtDesc_door},
    {FLAG_SILPH_6F_DOOR, sEvtName_SILPH_6F_DOOR, sEvtDesc_door},
    {FLAG_SILPH_7F_DOOR_1, sEvtName_SILPH_7F_DOOR_1, sEvtDesc_door},
    {FLAG_SILPH_7F_DOOR_2, sEvtName_SILPH_7F_DOOR_2, sEvtDesc_door},
    {FLAG_SILPH_7F_DOOR_3, sEvtName_SILPH_7F_DOOR_3, sEvtDesc_door},
    {FLAG_SILPH_8F_DOOR, sEvtName_SILPH_8F_DOOR, sEvtDesc_door},
    {FLAG_SILPH_9F_DOOR_1, sEvtName_SILPH_9F_DOOR_1, sEvtDesc_door},
    {FLAG_SILPH_9F_DOOR_2, sEvtName_SILPH_9F_DOOR_2, sEvtDesc_door},
    {FLAG_SILPH_9F_DOOR_3, sEvtName_SILPH_9F_DOOR_3, sEvtDesc_door},
    {FLAG_SILPH_9F_DOOR_4, sEvtName_SILPH_9F_DOOR_4, sEvtDesc_door},
    {FLAG_SILPH_10F_DOOR, sEvtName_SILPH_10F_DOOR, sEvtDesc_door},
    {FLAG_SILPH_11F_DOOR, sEvtName_SILPH_11F_DOOR, sEvtDesc_door},
};

static const struct RhDebugEvent sEvents_k_plant[] =
{
    {FLAG_HIDE_POWER_PLANT_ELECTRODE_1, sEvtName_HIDE_POWER_PLANT_ELECTRODE_1, sEvtDesc_hide},
    {FLAG_HIDE_POWER_PLANT_ELECTRODE_2, sEvtName_HIDE_POWER_PLANT_ELECTRODE_2, sEvtDesc_hide},
    {FLAG_FOUGHT_POWER_PLANT_ELECTRODE_1, sEvtName_FOUGHT_POWER_PLANT_ELECTRODE_1, sEvtDesc_fought},
    {FLAG_FOUGHT_POWER_PLANT_ELECTRODE_2, sEvtName_FOUGHT_POWER_PLANT_ELECTRODE_2, sEvtDesc_fought},
};

static const struct RhDebugEvent sEvents_k_seafoam[] =
{
    {FLAG_HIDE_SEAFOAM_1F_BOULDER_1, sEvtName_HIDE_SEAFOAM_1F_BOULDER_1, sEvtDesc_boulder},
    {FLAG_HIDE_SEAFOAM_1F_BOULDER_2, sEvtName_HIDE_SEAFOAM_1F_BOULDER_2, sEvtDesc_boulder},
    {FLAG_HIDE_SEAFOAM_B1F_BOULDER_1, sEvtName_HIDE_SEAFOAM_B1F_BOULDER_1, sEvtDesc_boulder},
    {FLAG_HIDE_SEAFOAM_B1F_BOULDER_2, sEvtName_HIDE_SEAFOAM_B1F_BOULDER_2, sEvtDesc_boulder},
    {FLAG_HIDE_SEAFOAM_B2F_BOULDER_1, sEvtName_HIDE_SEAFOAM_B2F_BOULDER_1, sEvtDesc_boulder},
    {FLAG_HIDE_SEAFOAM_B2F_BOULDER_2, sEvtName_HIDE_SEAFOAM_B2F_BOULDER_2, sEvtDesc_boulder},
    {FLAG_HIDE_SEAFOAM_B3F_BOULDER_1, sEvtName_HIDE_SEAFOAM_B3F_BOULDER_1, sEvtDesc_boulder},
    {FLAG_HIDE_SEAFOAM_B3F_BOULDER_2, sEvtName_HIDE_SEAFOAM_B3F_BOULDER_2, sEvtDesc_boulder},
    {FLAG_HIDE_SEAFOAM_B3F_BOULDER_3, sEvtName_HIDE_SEAFOAM_B3F_BOULDER_3, sEvtDesc_boulder},
    {FLAG_HIDE_SEAFOAM_B3F_BOULDER_4, sEvtName_HIDE_SEAFOAM_B3F_BOULDER_4, sEvtDesc_boulder},
    {FLAG_HIDE_SEAFOAM_B3F_BOULDER_5, sEvtName_HIDE_SEAFOAM_B3F_BOULDER_5, sEvtDesc_boulder},
    {FLAG_HIDE_SEAFOAM_B3F_BOULDER_6, sEvtName_HIDE_SEAFOAM_B3F_BOULDER_6, sEvtDesc_boulder},
    {FLAG_HIDE_SEAFOAM_B4F_BOULDER_1, sEvtName_HIDE_SEAFOAM_B4F_BOULDER_1, sEvtDesc_boulder},
    {FLAG_HIDE_SEAFOAM_B4F_BOULDER_2, sEvtName_HIDE_SEAFOAM_B4F_BOULDER_2, sEvtDesc_boulder},
    {FLAG_STOPPED_SEAFOAM_B3F_CURRENT, sEvtName_STOPPED_SEAFOAM_B3F_CURRENT, sEvtDesc_current},
    {FLAG_STOPPED_SEAFOAM_B4F_CURRENT, sEvtName_STOPPED_SEAFOAM_B4F_CURRENT, sEvtDesc_current},
};

static const struct RhDebugEvent sEvents_k_cinnabar[] =
{
    {FLAG_HIDE_CINNABAR_BILL, sEvtName_HIDE_CINNABAR_BILL, sEvtDesc_hide},
    {FLAG_HIDE_CINNABAR_SEAGALLOP, sEvtName_HIDE_CINNABAR_SEAGALLOP, sEvtDesc_hide},
    {FLAG_HIDE_CINNABAR_POKECENTER_BILL, sEvtName_HIDE_CINNABAR_POKECENTER_BILL, sEvtDesc_hide},
    {FLAG_POKEMON_MANSION_SWITCH_STATE, sEvtName_POKEMON_MANSION_SWITCH_STATE, sEvtDesc_sys},
    {FLAG_CINNABAR_GYM_QUIZ_1, sEvtName_CINNABAR_GYM_QUIZ_1, sEvtDesc_quiz},
    {FLAG_CINNABAR_GYM_QUIZ_2, sEvtName_CINNABAR_GYM_QUIZ_2, sEvtDesc_quiz},
    {FLAG_CINNABAR_GYM_QUIZ_3, sEvtName_CINNABAR_GYM_QUIZ_3, sEvtDesc_quiz},
    {FLAG_CINNABAR_GYM_QUIZ_4, sEvtName_CINNABAR_GYM_QUIZ_4, sEvtDesc_quiz},
    {FLAG_CINNABAR_GYM_QUIZ_5, sEvtName_CINNABAR_GYM_QUIZ_5, sEvtDesc_quiz},
    {FLAG_CINNABAR_GYM_QUIZ_6, sEvtName_CINNABAR_GYM_QUIZ_6, sEvtDesc_quiz},
};

static const struct RhDebugEvent sEvents_k_viridian[] =
{
    {FLAG_HIDE_VIRIDIAN_GIOVANNI, sEvtName_HIDE_VIRIDIAN_GIOVANNI, sEvtDesc_hide},
};

static const struct RhDebugEvent sEvents_k_vr[] =
{
    {FLAG_HIDE_VICTORY_ROAD_2F_BOULDER, sEvtName_HIDE_VICTORY_ROAD_2F_BOULDER, sEvtDesc_boulder},
    {FLAG_HIDE_VICTORY_ROAD_3F_BOULDER, sEvtName_HIDE_VICTORY_ROAD_3F_BOULDER, sEvtDesc_boulder},
};

static const struct RhDebugEvent sEvents_k_miscrocket[] =
{
    {FLAG_HIDE_MISC_KANTO_ROCKETS, sEvtName_HIDE_MISC_KANTO_ROCKETS, sEvtDesc_hide},
};

static const struct RhDebugEvent sEvents_s_trades[] =
{
    {FLAG_DID_MIMIEN_TRADE, sEvtName_DID_MIMIEN_TRADE, sEvtDesc_trade},
    {FLAG_DID_ZYNX_TRADE, sEvtName_DID_ZYNX_TRADE, sEvtDesc_trade},
    {FLAG_DID_MS_NIDO_TRADE, sEvtName_DID_MS_NIDO_TRADE, sEvtDesc_trade},
    {FLAG_DID_CH_DING_TRADE, sEvtName_DID_CH_DING_TRADE, sEvtDesc_trade},
    {FLAG_DID_NINA_TRADE, sEvtName_DID_NINA_TRADE, sEvtDesc_trade},
    {FLAG_DID_MARC_TRADE, sEvtName_DID_MARC_TRADE, sEvtDesc_trade},
    {FLAG_DID_ESPHERE_TRADE, sEvtName_DID_ESPHERE_TRADE, sEvtDesc_trade},
    {FLAG_DID_TANGENY_TRADE, sEvtName_DID_TANGENY_TRADE, sEvtDesc_trade},
    {FLAG_DID_SEELOR_TRADE, sEvtName_DID_SEELOR_TRADE, sEvtDesc_trade},
};

static const struct RhDebugEvent sEvents_s_tutors[] =
{
    {FLAG_TUTOR_DOUBLE_EDGE, sEvtName_TUTOR_DOUBLE_EDGE, sEvtDesc_tutor},
    {FLAG_TUTOR_THUNDER_WAVE, sEvtName_TUTOR_THUNDER_WAVE, sEvtDesc_tutor},
    {FLAG_TUTOR_ROCK_SLIDE, sEvtName_TUTOR_ROCK_SLIDE, sEvtDesc_tutor},
    {FLAG_TUTOR_EXPLOSION, sEvtName_TUTOR_EXPLOSION, sEvtDesc_tutor},
    {FLAG_TUTOR_MEGA_PUNCH, sEvtName_TUTOR_MEGA_PUNCH, sEvtDesc_tutor},
    {FLAG_TUTOR_MEGA_KICK, sEvtName_TUTOR_MEGA_KICK, sEvtDesc_tutor},
    {FLAG_TUTOR_DREAM_EATER, sEvtName_TUTOR_DREAM_EATER, sEvtDesc_tutor},
    {FLAG_TUTOR_SOFT_BOILED, sEvtName_TUTOR_SOFT_BOILED, sEvtDesc_tutor},
    {FLAG_TUTOR_SUBSTITUTE, sEvtName_TUTOR_SUBSTITUTE, sEvtDesc_tutor},
    {FLAG_TUTOR_SWORDS_DANCE, sEvtName_TUTOR_SWORDS_DANCE, sEvtDesc_tutor},
    {FLAG_TUTOR_SEISMIC_TOSS, sEvtName_TUTOR_SEISMIC_TOSS, sEvtDesc_tutor},
    {FLAG_TUTOR_COUNTER, sEvtName_TUTOR_COUNTER, sEvtDesc_tutor},
    {FLAG_TUTOR_METRONOME, sEvtName_TUTOR_METRONOME, sEvtDesc_tutor},
    {FLAG_TUTOR_MIMIC, sEvtName_TUTOR_MIMIC, sEvtDesc_tutor},
    {FLAG_TUTOR_BODY_SLAM, sEvtName_TUTOR_BODY_SLAM, sEvtDesc_tutor},
    {FLAG_TUTOR_FRENZY_PLANT, sEvtName_TUTOR_FRENZY_PLANT, sEvtDesc_tutor},
    {FLAG_TUTOR_BLAST_BURN, sEvtName_TUTOR_BLAST_BURN, sEvtDesc_tutor},
    {FLAG_TUTOR_HYDRO_CANNON, sEvtName_TUTOR_HYDRO_CANNON, sEvtDesc_tutor},
    {FLAG_LEARNED_ALL_MOVES_AT_CAPE_BRINK, sEvtName_LEARNED_ALL_MOVES_AT_CAPE_BRINK, sEvtDesc_tutor},
};

static const struct RhDebugEvent sEvents_s_gymtms[] =
{
    {FLAG_GOT_TM39_FROM_BROCK, sEvtName_GOT_TM39_FROM_BROCK, sEvtDesc_got},
    {FLAG_GOT_TM03_FROM_MISTY, sEvtName_GOT_TM03_FROM_MISTY, sEvtDesc_got},
    {FLAG_GOT_TM34_FROM_SURGE, sEvtName_GOT_TM34_FROM_SURGE, sEvtDesc_got},
    {FLAG_GOT_TM19_FROM_ERIKA, sEvtName_GOT_TM19_FROM_ERIKA, sEvtDesc_got},
    {FLAG_GOT_TM06_FROM_KOGA, sEvtName_GOT_TM06_FROM_KOGA, sEvtDesc_got},
    {FLAG_GOT_TM04_FROM_SABRINA, sEvtName_GOT_TM04_FROM_SABRINA, sEvtDesc_got},
    {FLAG_GOT_TM38_FROM_BLAINE, sEvtName_GOT_TM38_FROM_BLAINE, sEvtDesc_got},
    {FLAG_GOT_TM26_FROM_GIOVANNI, sEvtName_GOT_TM26_FROM_GIOVANNI, sEvtDesc_got},
};

static const struct RhDebugEvent sEvents_s_aides[] =
{
    {FLAG_HIDE_VERMILION_CITY_OAKS_AIDE, sEvtName_HIDE_VERMILION_CITY_OAKS_AIDE, sEvtDesc_hide},
    {FLAG_TALKED_TO_OAKS_AIDE_IN_VERMILION, sEvtName_TALKED_TO_OAKS_AIDE_IN_VERMILION, sEvtDesc_sys},
    {FLAG_GOT_EXP_SHARE_FROM_OAKS_AIDE, sEvtName_GOT_EXP_SHARE_FROM_OAKS_AIDE, sEvtDesc_got},
    {FLAG_GOT_EVERSTONE_FROM_OAKS_AIDE, sEvtName_GOT_EVERSTONE_FROM_OAKS_AIDE, sEvtDesc_got},
    {FLAG_GOT_AMULET_COIN_FROM_OAKS_AIDE, sEvtName_GOT_AMULET_COIN_FROM_OAKS_AIDE, sEvtDesc_got},
    {FLAG_OAK_SAW_DEX_COMPLETION, sEvtName_OAK_SAW_DEX_COMPLETION, sEvtDesc_sys},
    {FLAG_GOT_SHINY_CHARM, sEvtName_GOT_SHINY_CHARM, sEvtDesc_got},
};

static const struct RhDebugEvent sEvents_s_fanclub[] =
{
    {FLAG_HIDE_SAFFRON_FAN_CLUB_BLACK_BELT, sEvtName_HIDE_SAFFRON_FAN_CLUB_BLACK_BELT, sEvtDesc_hide},
    {FLAG_HIDE_SAFFRON_FAN_CLUB_ROCKER, sEvtName_HIDE_SAFFRON_FAN_CLUB_ROCKER, sEvtDesc_hide},
    {FLAG_HIDE_SAFFRON_FAN_CLUB_WOMAN, sEvtName_HIDE_SAFFRON_FAN_CLUB_WOMAN, sEvtDesc_hide},
    {FLAG_HIDE_SAFFRON_FAN_CLUB_BEAUTY, sEvtName_HIDE_SAFFRON_FAN_CLUB_BEAUTY, sEvtDesc_hide},
    {FLAG_GOT_TITAN, sEvtName_GOT_TITAN, sEvtDesc_got},
};

static const struct RhDebugEvent sEvents_s_daycare[] =
{
    {FLAG_PENDING_DAYCARE_EGG, sEvtName_PENDING_DAYCARE_EGG, sEvtDesc_sys},
};

static const struct RhDebugEvent sEvents_s_misc[] =
{
    {FLAG_GOT_TM29_FROM_MR_PSYCHIC, sEvtName_GOT_TM29_FROM_MR_PSYCHIC, sEvtDesc_got},
    {FLAG_GOT_TM33_FROM_THIRSTY_GIRL, sEvtName_GOT_TM33_FROM_THIRSTY_GIRL, sEvtDesc_got},
    {FLAG_GOT_TM20_FROM_THIRSTY_GIRL, sEvtName_GOT_TM20_FROM_THIRSTY_GIRL, sEvtDesc_got},
    {FLAG_GOT_TM16_FROM_THIRSTY_GIRL, sEvtName_GOT_TM16_FROM_THIRSTY_GIRL, sEvtDesc_got},
    {FLAG_GOT_TM27, sEvtName_GOT_TM27, sEvtDesc_got},
    {FLAG_TALKED_TO_TEA_LADY_AFTER_HOF, sEvtName_TALKED_TO_TEA_LADY_AFTER_HOF, sEvtDesc_sys},
    {FLAG_MET_STICKER_MAN, sEvtName_MET_STICKER_MAN, sEvtDesc_sys},
    {FLAG_LEARNED_YES_NAH_CHANSEY, sEvtName_LEARNED_YES_NAH_CHANSEY, sEvtDesc_sys},
};

static const struct RhDebugEvent sEvents_v_sys[] =
{
    {FLAG_SYS_SEVII_MAP_123, sEvtName_SYS_SEVII_MAP_123, sEvtDesc_sys},
    {FLAG_SYS_SEVII_MAP_4567, sEvtName_SYS_SEVII_MAP_4567, sEvtDesc_sys},
    {FLAG_SYS_NATIONAL_DEX, sEvtName_SYS_NATIONAL_DEX, sEvtDesc_sys},
    {FLAG_SYS_CAN_LINK_WITH_RS, sEvtName_SYS_CAN_LINK_WITH_RS, sEvtDesc_sys},
    {FLAG_SYS_UNLOCKED_TANOBY_RUINS, sEvtName_SYS_UNLOCKED_TANOBY_RUINS, sEvtDesc_sys},
    {FLAG_SEVII_DETOUR_FINISHED, sEvtName_SEVII_DETOUR_FINISHED, sEvtDesc_sys},
};

static const struct RhDebugEvent sEvents_v_tickets[] =
{
    {FLAG_RECEIVED_AURORA_TICKET, sEvtName_RECEIVED_AURORA_TICKET, sEvtDesc_got},
    {FLAG_SHOWN_AURORA_TICKET, sEvtName_SHOWN_AURORA_TICKET, sEvtDesc_sys},
    {FLAG_RECEIVED_MYSTIC_TICKET, sEvtName_RECEIVED_MYSTIC_TICKET, sEvtDesc_got},
    {FLAG_SHOWN_MYSTIC_TICKET, sEvtName_SHOWN_MYSTIC_TICKET, sEvtDesc_sys},
    {FLAG_RECEIVED_OLD_SEA_MAP, sEvtName_RECEIVED_OLD_SEA_MAP, sEvtDesc_got},
    {FLAG_HIDE_MG_DELIVERYMEN, sEvtName_HIDE_MG_DELIVERYMEN, sEvtDesc_hide},
};

static const struct RhDebugEvent sEvents_v_celio[] =
{
    {FLAG_HIDE_ONE_ISLAND_BILL, sEvtName_HIDE_ONE_ISLAND_BILL, sEvtDesc_hide},
    {FLAG_HIDE_ONE_ISLAND_POKECENTER_BILL, sEvtName_HIDE_ONE_ISLAND_POKECENTER_BILL, sEvtDesc_hide},
    {FLAG_HIDE_ONE_ISLAND_POKECENTER_CELIO, sEvtName_HIDE_ONE_ISLAND_POKECENTER_CELIO, sEvtDesc_hide},
    {FLAG_HIDE_RUBY, sEvtName_HIDE_RUBY, sEvtDesc_hide},
    {FLAG_GOT_RUBY, sEvtName_GOT_RUBY, sEvtDesc_got},
    {FLAG_HIDE_SAPPHIRE, sEvtName_HIDE_SAPPHIRE, sEvtDesc_hide},
    {FLAG_RECOVERED_SAPPHIRE, sEvtName_RECOVERED_SAPPHIRE, sEvtDesc_sys},
    {FLAG_HIDE_MT_EMBER_EXTERIOR_ROCKETS, sEvtName_HIDE_MT_EMBER_EXTERIOR_ROCKETS, sEvtDesc_hide},
};

static const struct RhDebugEvent sEvents_v_lostelle[] =
{
    {FLAG_HIDE_TWO_ISLAND_GAME_CORNER_BIKER, sEvtName_HIDE_TWO_ISLAND_GAME_CORNER_BIKER, sEvtDesc_hide},
    {FLAG_HIDE_TWO_ISLAND_GAME_CORNER_LOSTELLE, sEvtName_HIDE_TWO_ISLAND_GAME_CORNER_LOSTELLE, sEvtDesc_hide},
    {FLAG_HIDE_LOSTELLE_IN_HER_HOME, sEvtName_HIDE_LOSTELLE_IN_HER_HOME, sEvtDesc_hide},
    {FLAG_HIDE_LOSTELLE_IN_BERRY_FOREST, sEvtName_HIDE_LOSTELLE_IN_BERRY_FOREST, sEvtDesc_hide},
    {FLAG_HIDE_THREE_ISLAND_BIKERS, sEvtName_HIDE_THREE_ISLAND_BIKERS, sEvtDesc_hide},
    {FLAG_HIDE_THREE_ISLAND_ANTIBIKERS, sEvtName_HIDE_THREE_ISLAND_ANTIBIKERS, sEvtDesc_hide},
    {FLAG_HIDE_THREE_ISLAND_LONE_BIKER, sEvtName_HIDE_THREE_ISLAND_LONE_BIKER, sEvtDesc_hide},
    {FLAG_HIDE_TWO_ISLAND_WOMAN, sEvtName_HIDE_TWO_ISLAND_WOMAN, sEvtDesc_hide},
    {FLAG_HIDE_TWO_ISLAND_BEAUTY, sEvtName_HIDE_TWO_ISLAND_BEAUTY, sEvtDesc_hide},
    {FLAG_HIDE_TWO_ISLAND_POKE_MANIAC, sEvtName_HIDE_TWO_ISLAND_POKE_MANIAC, sEvtDesc_hide},
    {FLAG_RESCUED_LOSTELLE, sEvtName_RESCUED_LOSTELLE, sEvtDesc_sys},
    {FLAG_VISITED_TWO_ISLAND, sEvtName_VISITED_TWO_ISLAND, sEvtDesc_sys},
    {FLAG_GOT_FULL_RESTORE_FROM_THREE_ISLAND_DEFENDER, sEvtName_GOT_FULL_RESTORE_FROM_THREE_ISLAND_DEFENDER, sEvtDesc_got},
};

static const struct RhDebugEvent sEvents_v_rockets[] =
{
    {FLAG_HIDE_FIVE_ISLAND_ROCKETS, sEvtName_HIDE_FIVE_ISLAND_ROCKETS, sEvtDesc_hide},
    {FLAG_HIDE_ICEFALL_CAVE_LORELEI, sEvtName_HIDE_ICEFALL_CAVE_LORELEI, sEvtDesc_hide},
    {FLAG_HIDE_LORELEI_IN_HER_HOUSE, sEvtName_HIDE_LORELEI_IN_HER_HOUSE, sEvtDesc_hide},
    {FLAG_HIDE_ICEFALL_CAVE_ROCKETS, sEvtName_HIDE_ICEFALL_CAVE_ROCKETS, sEvtDesc_hide},
    {FLAG_DEFEATED_ROCKETS_IN_WAREHOUSE, sEvtName_DEFEATED_ROCKETS_IN_WAREHOUSE, sEvtDesc_defeat},
    {FLAG_UNLOCKED_ROCKET_WAREHOUSE, sEvtName_UNLOCKED_ROCKET_WAREHOUSE, sEvtDesc_sys},
    {FLAG_TALKED_TO_LORELEI_AFTER_WAREHOUSE, sEvtName_TALKED_TO_LORELEI_AFTER_WAREHOUSE, sEvtDesc_sys},
};

static const struct RhDebugEvent sEvents_v_selphy[] =
{
    {FLAG_HIDE_LOST_CAVE_SELPHY, sEvtName_HIDE_LOST_CAVE_SELPHY, sEvtDesc_hide},
    {FLAG_HIDE_RESORT_GORGEOUS_SELPHY, sEvtName_HIDE_RESORT_GORGEOUS_SELPHY, sEvtDesc_hide},
    {FLAG_HIDE_RESORT_GORGEOUS_INSIDE_SELPHY, sEvtName_HIDE_RESORT_GORGEOUS_INSIDE_SELPHY, sEvtDesc_hide},
    {FLAG_HIDE_SELPHYS_BUTLER, sEvtName_HIDE_SELPHYS_BUTLER, sEvtDesc_hide},
    {FLAG_GOT_TOGEPI_EGG, sEvtName_GOT_TOGEPI_EGG, sEvtDesc_got},
};

static const struct RhDebugEvent sEvents_v_ruin[] =
{
    {FLAG_HIDE_RUIN_VALLEY_SCIENTIST, sEvtName_HIDE_RUIN_VALLEY_SCIENTIST, sEvtDesc_hide},
    {FLAG_HIDE_DOTTED_HOLE_SCIENTIST, sEvtName_HIDE_DOTTED_HOLE_SCIENTIST, sEvtDesc_hide},
    {FLAG_USED_CUT_ON_RUIN_VALLEY_BRAILLE, sEvtName_USED_CUT_ON_RUIN_VALLEY_BRAILLE, sEvtDesc_sys},
};

static const struct RhDebugEvent sEvents_v_rivals[] =
{
    {FLAG_HIDE_FOUR_ISLAND_RIVAL, sEvtName_HIDE_FOUR_ISLAND_RIVAL, sEvtDesc_hide},
    {FLAG_HIDE_SIX_ISLAND_POKECENTER_RIVAL, sEvtName_HIDE_SIX_ISLAND_POKECENTER_RIVAL, sEvtDesc_hide},
};

static const struct RhDebugEvent sEvents_v_misc[] =
{
    {FLAG_TWO_ISLAND_SHOP_INTRODUCED, sEvtName_TWO_ISLAND_SHOP_INTRODUCED, sEvtDesc_shop},
    {FLAG_TWO_ISLAND_SHOP_EXPANDED_1, sEvtName_TWO_ISLAND_SHOP_EXPANDED_1, sEvtDesc_shop},
    {FLAG_TWO_ISLAND_SHOP_EXPANDED_2, sEvtName_TWO_ISLAND_SHOP_EXPANDED_2, sEvtDesc_shop},
    {FLAG_TWO_ISLAND_SHOP_EXPANDED_3, sEvtName_TWO_ISLAND_SHOP_EXPANDED_3, sEvtDesc_shop},
    {FLAG_GOT_TM42_AT_MEMORIAL_PILLAR, sEvtName_GOT_TM42_AT_MEMORIAL_PILLAR, sEvtDesc_got},
    {FLAG_GOT_MOON_STONE_FROM_JOYFUL_GAME_CORNER, sEvtName_GOT_MOON_STONE_FROM_JOYFUL_GAME_CORNER, sEvtDesc_got},
    {FLAG_GOT_NEST_BALL_FROM_WATER_PATH_HOUSE_1, sEvtName_GOT_NEST_BALL_FROM_WATER_PATH_HOUSE_1, sEvtDesc_got},
    {FLAG_GOT_NUGGET_FROM_DUNSPARCE_TUNNEL, sEvtName_GOT_NUGGET_FROM_DUNSPARCE_TUNNEL, sEvtDesc_got},
};

static const struct RhDebugEvent sEvents_w_towns[] =
{
    {FLAG_WORLD_MAP_PALLET_TOWN, sEvtName_WORLD_MAP_PALLET_TOWN, sEvtDesc_map},
    {FLAG_WORLD_MAP_VIRIDIAN_CITY, sEvtName_WORLD_MAP_VIRIDIAN_CITY, sEvtDesc_map},
    {FLAG_WORLD_MAP_PEWTER_CITY, sEvtName_WORLD_MAP_PEWTER_CITY, sEvtDesc_map},
    {FLAG_WORLD_MAP_CERULEAN_CITY, sEvtName_WORLD_MAP_CERULEAN_CITY, sEvtDesc_map},
    {FLAG_WORLD_MAP_LAVENDER_TOWN, sEvtName_WORLD_MAP_LAVENDER_TOWN, sEvtDesc_map},
    {FLAG_WORLD_MAP_VERMILION_CITY, sEvtName_WORLD_MAP_VERMILION_CITY, sEvtDesc_map},
    {FLAG_WORLD_MAP_CELADON_CITY, sEvtName_WORLD_MAP_CELADON_CITY, sEvtDesc_map},
    {FLAG_WORLD_MAP_FUCHSIA_CITY, sEvtName_WORLD_MAP_FUCHSIA_CITY, sEvtDesc_map},
    {FLAG_WORLD_MAP_CINNABAR_ISLAND, sEvtName_WORLD_MAP_CINNABAR_ISLAND, sEvtDesc_map},
    {FLAG_WORLD_MAP_INDIGO_PLATEAU_EXTERIOR, sEvtName_WORLD_MAP_INDIGO_PLATEAU_EXTERIOR, sEvtDesc_map},
    {FLAG_WORLD_MAP_SAFFRON_CITY, sEvtName_WORLD_MAP_SAFFRON_CITY, sEvtDesc_map},
    {FLAG_WORLD_MAP_ROUTE4_POKEMON_CENTER_1F, sEvtName_WORLD_MAP_ROUTE4_POKEMON_CENTER_1F, sEvtDesc_map},
    {FLAG_WORLD_MAP_ROUTE10_POKEMON_CENTER_1F, sEvtName_WORLD_MAP_ROUTE10_POKEMON_CENTER_1F, sEvtDesc_map},
};

static const struct RhDebugEvent sEvents_w_dung[] =
{
    {FLAG_WORLD_MAP_VIRIDIAN_FOREST, sEvtName_WORLD_MAP_VIRIDIAN_FOREST, sEvtDesc_map},
    {FLAG_WORLD_MAP_MT_MOON_1F, sEvtName_WORLD_MAP_MT_MOON_1F, sEvtDesc_map},
    {FLAG_WORLD_MAP_SSANNE_EXTERIOR, sEvtName_WORLD_MAP_SSANNE_EXTERIOR, sEvtDesc_map},
    {FLAG_WORLD_MAP_UNDERGROUND_PATH_NORTH_SOUTH_TUNNEL, sEvtName_WORLD_MAP_UNDERGROUND_PATH_NORTH_SOUTH_TUNNEL, sEvtDesc_map},
    {FLAG_WORLD_MAP_UNDERGROUND_PATH_EAST_WEST_TUNNEL, sEvtName_WORLD_MAP_UNDERGROUND_PATH_EAST_WEST_TUNNEL, sEvtDesc_map},
    {FLAG_WORLD_MAP_DIGLETTS_CAVE_B1F, sEvtName_WORLD_MAP_DIGLETTS_CAVE_B1F, sEvtDesc_map},
    {FLAG_WORLD_MAP_VICTORY_ROAD_1F, sEvtName_WORLD_MAP_VICTORY_ROAD_1F, sEvtDesc_map},
    {FLAG_WORLD_MAP_ROCKET_HIDEOUT_B1F, sEvtName_WORLD_MAP_ROCKET_HIDEOUT_B1F, sEvtDesc_map},
    {FLAG_WORLD_MAP_SILPH_CO_1F, sEvtName_WORLD_MAP_SILPH_CO_1F, sEvtDesc_map},
    {FLAG_WORLD_MAP_POKEMON_MANSION_1F, sEvtName_WORLD_MAP_POKEMON_MANSION_1F, sEvtDesc_map},
    {FLAG_WORLD_MAP_SAFARI_ZONE_CENTER, sEvtName_WORLD_MAP_SAFARI_ZONE_CENTER, sEvtDesc_map},
    {FLAG_WORLD_MAP_POKEMON_LEAGUE_LORELEIS_ROOM, sEvtName_WORLD_MAP_POKEMON_LEAGUE_LORELEIS_ROOM, sEvtDesc_map},
    {FLAG_WORLD_MAP_ROCK_TUNNEL_1F, sEvtName_WORLD_MAP_ROCK_TUNNEL_1F, sEvtDesc_map},
    {FLAG_WORLD_MAP_SEAFOAM_ISLANDS_1F, sEvtName_WORLD_MAP_SEAFOAM_ISLANDS_1F, sEvtDesc_map},
    {FLAG_WORLD_MAP_POKEMON_TOWER_1F, sEvtName_WORLD_MAP_POKEMON_TOWER_1F, sEvtDesc_map},
    {FLAG_WORLD_MAP_CERULEAN_CAVE_1F, sEvtName_WORLD_MAP_CERULEAN_CAVE_1F, sEvtDesc_map},
    {FLAG_WORLD_MAP_POWER_PLANT, sEvtName_WORLD_MAP_POWER_PLANT, sEvtDesc_map},
};

static const struct RhDebugEvent sEvents_w_sevii[] =
{
    {FLAG_WORLD_MAP_ONE_ISLAND, sEvtName_WORLD_MAP_ONE_ISLAND, sEvtDesc_map},
    {FLAG_WORLD_MAP_TWO_ISLAND, sEvtName_WORLD_MAP_TWO_ISLAND, sEvtDesc_map},
    {FLAG_WORLD_MAP_THREE_ISLAND, sEvtName_WORLD_MAP_THREE_ISLAND, sEvtDesc_map},
    {FLAG_WORLD_MAP_FOUR_ISLAND, sEvtName_WORLD_MAP_FOUR_ISLAND, sEvtDesc_map},
    {FLAG_WORLD_MAP_FIVE_ISLAND, sEvtName_WORLD_MAP_FIVE_ISLAND, sEvtDesc_map},
    {FLAG_WORLD_MAP_SIX_ISLAND, sEvtName_WORLD_MAP_SIX_ISLAND, sEvtDesc_map},
    {FLAG_WORLD_MAP_SEVEN_ISLAND, sEvtName_WORLD_MAP_SEVEN_ISLAND, sEvtDesc_map},
    {FLAG_WORLD_MAP_NAVEL_ROCK_EXTERIOR, sEvtName_WORLD_MAP_NAVEL_ROCK_EXTERIOR, sEvtDesc_map},
    {FLAG_WORLD_MAP_MT_EMBER_EXTERIOR, sEvtName_WORLD_MAP_MT_EMBER_EXTERIOR, sEvtDesc_map},
    {FLAG_WORLD_MAP_THREE_ISLAND_BERRY_FOREST, sEvtName_WORLD_MAP_THREE_ISLAND_BERRY_FOREST, sEvtDesc_map},
    {FLAG_WORLD_MAP_FOUR_ISLAND_ICEFALL_CAVE_ENTRANCE, sEvtName_WORLD_MAP_FOUR_ISLAND_ICEFALL_CAVE_ENTRANCE, sEvtDesc_map},
    {FLAG_WORLD_MAP_FIVE_ISLAND_ROCKET_WAREHOUSE, sEvtName_WORLD_MAP_FIVE_ISLAND_ROCKET_WAREHOUSE, sEvtDesc_map},
    {FLAG_WORLD_MAP_TRAINER_TOWER_LOBBY, sEvtName_WORLD_MAP_TRAINER_TOWER_LOBBY, sEvtDesc_map},
    {FLAG_WORLD_MAP_SIX_ISLAND_DOTTED_HOLE_1F, sEvtName_WORLD_MAP_SIX_ISLAND_DOTTED_HOLE_1F, sEvtDesc_map},
    {FLAG_WORLD_MAP_FIVE_ISLAND_LOST_CAVE_ENTRANCE, sEvtName_WORLD_MAP_FIVE_ISLAND_LOST_CAVE_ENTRANCE, sEvtDesc_map},
    {FLAG_WORLD_MAP_SIX_ISLAND_PATTERN_BUSH, sEvtName_WORLD_MAP_SIX_ISLAND_PATTERN_BUSH, sEvtDesc_map},
    {FLAG_WORLD_MAP_SIX_ISLAND_ALTERING_CAVE, sEvtName_WORLD_MAP_SIX_ISLAND_ALTERING_CAVE, sEvtDesc_map},
    {FLAG_WORLD_MAP_SEVEN_ISLAND_TANOBY_RUINS_MONEAN_CHAMBER, sEvtName_WORLD_MAP_SEVEN_ISLAND_TANOBY_RUINS_MONEAN_CHAMBER, sEvtDesc_map},
    {FLAG_WORLD_MAP_THREE_ISLAND_DUNSPARCE_TUNNEL, sEvtName_WORLD_MAP_THREE_ISLAND_DUNSPARCE_TUNNEL, sEvtDesc_map},
    {FLAG_WORLD_MAP_SEVEN_ISLAND_SEVAULT_CANYON_TANOBY_KEY, sEvtName_WORLD_MAP_SEVEN_ISLAND_SEVAULT_CANYON_TANOBY_KEY, sEvtDesc_map},
    {FLAG_WORLD_MAP_BIRTH_ISLAND_EXTERIOR, sEvtName_WORLD_MAP_BIRTH_ISLAND_EXTERIOR, sEvtDesc_map},
};

static const u8 sText_EvtFolder_EARLY[] = _("EARLY GAME");
static const u8 sText_EvtFolder_KANTO[] = _("KANTO STORY");
static const u8 sText_EvtFolder_BADGES[] = _("BADGES / LEAGUE");
static const u8 sText_EvtFolder_HMS[] = _("HMs / KEY ITEMS");
static const u8 sText_EvtFolder_SIDE[] = _("SIDE CONTENT");
static const u8 sText_EvtFolder_LEGENDS[] = _("LEGENDARIES");
static const u8 sText_EvtFolder_SEVII[] = _("SEVII / POSTGAME");
static const u8 sText_EvtFolder_WORLDMAP[] = _("WORLD MAP");
static const u8 sText_EvtFolder_SYSMISC[] = _("SYS MISC");
static const u8 sText_EvtKanto_MTMOON[] = _("MT MOON / FOSSILS");
static const u8 sText_EvtKanto_NUGGET[] = _("NUGGET BRIDGE");
static const u8 sText_EvtKanto_BILL[] = _("BILL");
static const u8 sText_EvtKanto_CERULEAN[] = _("CERULEAN");
static const u8 sText_EvtKanto_ANNE[] = _("SS ANNE");
static const u8 sText_EvtKanto_ROCKETS[] = _("ROCKETS / CORNER");
static const u8 sText_EvtKanto_FUJI[] = _("LAVENDER / FUJI");
static const u8 sText_EvtKanto_SNORLAX[] = _("SNORLAX");
static const u8 sText_EvtKanto_SILPH[] = _("SILPH / SAFFRON");
static const u8 sText_EvtKanto_PLANT[] = _("POWER PLANT");
static const u8 sText_EvtKanto_SEAFOAM[] = _("SEAFOAM");
static const u8 sText_EvtKanto_CINNABAR[] = _("CINNABAR");
static const u8 sText_EvtKanto_VIRIDIAN[] = _("VIRIDIAN GIOVANNI");
static const u8 sText_EvtKanto_VR[] = _("VICTORY ROAD");
static const u8 sText_EvtKanto_MISCROCKET[] = _("MISC KANTO ROCKETS");
static const u8 sText_EvtSide_TRADES[] = _("IN-GAME TRADES");
static const u8 sText_EvtSide_TUTORS[] = _("MOVE TUTORS");
static const u8 sText_EvtSide_GYMTMS[] = _("GYM LEADER TMs");
static const u8 sText_EvtSide_AIDES[] = _("OAKS AIDES");
static const u8 sText_EvtSide_FANCLUB[] = _("FAN CLUB");
static const u8 sText_EvtSide_DAYCARE[] = _("DAY CARE");
static const u8 sText_EvtSide_MISC[] = _("MISC SIDE");
static const u8 sText_EvtSevii_SYS[] = _("SYS / UNLOCK");
static const u8 sText_EvtSevii_TICKETS[] = _("TICKETS / MG");
static const u8 sText_EvtSevii_CELIO[] = _("ONE ISLAND / CELIO");
static const u8 sText_EvtSevii_LOSTELLE[] = _("LOSTELLE");
static const u8 sText_EvtSevii_ROCKETS[] = _("FIVE ISLAND ROCKETS");
static const u8 sText_EvtSevii_SELPHY[] = _("SELPHY");
static const u8 sText_EvtSevii_RUIN[] = _("RUIN / DOTTED HOLE");
static const u8 sText_EvtSevii_RIVALS[] = _("ISLAND RIVALS");
static const u8 sText_EvtSevii_MISC[] = _("SEVII MISC");
static const u8 sText_EvtMap_TOWNS[] = _("KANTO TOWNS");
static const u8 sText_EvtMap_DUNG[] = _("KANTO DUNGEONS");
static const u8 sText_EvtMap_SEVII[] = _("SEVII");

static const struct ListMenuItem sEventFolderItems[] =
{
    {sText_EvtFolder_EARLY, EVENT_FOLDER_EARLY},
    {sText_EvtFolder_KANTO, EVENT_FOLDER_KANTO},
    {sText_EvtFolder_BADGES, EVENT_FOLDER_BADGES},
    {sText_EvtFolder_HMS, EVENT_FOLDER_HMS},
    {sText_EvtFolder_SIDE, EVENT_FOLDER_SIDE},
    {sText_EvtFolder_LEGENDS, EVENT_FOLDER_LEGENDS},
    {sText_EvtFolder_SEVII, EVENT_FOLDER_SEVII},
    {sText_EvtFolder_WORLDMAP, EVENT_FOLDER_WORLDMAP},
    {sText_EvtFolder_SYSMISC, EVENT_FOLDER_SYSMISC},
    {sText_Back, LIST_CANCEL},
};

static const struct ListMenuItem sEventKantoItems[] =
{
    {sText_EvtKanto_MTMOON, EVENT_KANTO_MTMOON},
    {sText_EvtKanto_NUGGET, EVENT_KANTO_NUGGET},
    {sText_EvtKanto_BILL, EVENT_KANTO_BILL},
    {sText_EvtKanto_CERULEAN, EVENT_KANTO_CERULEAN},
    {sText_EvtKanto_ANNE, EVENT_KANTO_ANNE},
    {sText_EvtKanto_ROCKETS, EVENT_KANTO_ROCKETS},
    {sText_EvtKanto_FUJI, EVENT_KANTO_FUJI},
    {sText_EvtKanto_SNORLAX, EVENT_KANTO_SNORLAX},
    {sText_EvtKanto_SILPH, EVENT_KANTO_SILPH},
    {sText_EvtKanto_PLANT, EVENT_KANTO_PLANT},
    {sText_EvtKanto_SEAFOAM, EVENT_KANTO_SEAFOAM},
    {sText_EvtKanto_CINNABAR, EVENT_KANTO_CINNABAR},
    {sText_EvtKanto_VIRIDIAN, EVENT_KANTO_VIRIDIAN},
    {sText_EvtKanto_VR, EVENT_KANTO_VR},
    {sText_EvtKanto_MISCROCKET, EVENT_KANTO_MISCROCKET},
    {sText_Back, LIST_CANCEL},
};

static const struct ListMenuItem sEventSideItems[] =
{
    {sText_EvtSide_TRADES, EVENT_SIDE_TRADES},
    {sText_EvtSide_TUTORS, EVENT_SIDE_TUTORS},
    {sText_EvtSide_GYMTMS, EVENT_SIDE_GYMTMS},
    {sText_EvtSide_AIDES, EVENT_SIDE_AIDES},
    {sText_EvtSide_FANCLUB, EVENT_SIDE_FANCLUB},
    {sText_EvtSide_DAYCARE, EVENT_SIDE_DAYCARE},
    {sText_EvtSide_MISC, EVENT_SIDE_MISC},
    {sText_Back, LIST_CANCEL},
};

static const struct ListMenuItem sEventSeviiItems[] =
{
    {sText_EvtSevii_SYS, EVENT_SEVII_SYS},
    {sText_EvtSevii_TICKETS, EVENT_SEVII_TICKETS},
    {sText_EvtSevii_CELIO, EVENT_SEVII_CELIO},
    {sText_EvtSevii_LOSTELLE, EVENT_SEVII_LOSTELLE},
    {sText_EvtSevii_ROCKETS, EVENT_SEVII_ROCKETS},
    {sText_EvtSevii_SELPHY, EVENT_SEVII_SELPHY},
    {sText_EvtSevii_RUIN, EVENT_SEVII_RUIN},
    {sText_EvtSevii_RIVALS, EVENT_SEVII_RIVALS},
    {sText_EvtSevii_MISC, EVENT_SEVII_MISC},
    {sText_Back, LIST_CANCEL},
};

static const struct ListMenuItem sEventMapItems[] =
{
    {sText_EvtMap_TOWNS, EVENT_MAP_TOWNS},
    {sText_EvtMap_DUNG, EVENT_MAP_DUNG},
    {sText_EvtMap_SEVII, EVENT_MAP_SEVII},
    {sText_Back, LIST_CANCEL},
};

// Used by menu: folder has subs if KANTO/SIDE/SEVII/WORLDMAP
static const bool8 sEventFolderHasSubs[] =
{
    0, // EVENT_FOLDER_EARLY
    1, // EVENT_FOLDER_KANTO
    0, // EVENT_FOLDER_BADGES
    0, // EVENT_FOLDER_HMS
    1, // EVENT_FOLDER_SIDE
    0, // EVENT_FOLDER_LEGENDS
    1, // EVENT_FOLDER_SEVII
    1, // EVENT_FOLDER_WORLDMAP
    0, // EVENT_FOLDER_SYSMISC
};

static const struct RhDebugEvent * const sEventFolderFlatTables[] =
{
    sEvents_early,
    NULL,
    sEvents_badges,
    sEvents_hms,
    NULL,
    sEvents_legends,
    NULL,
    NULL,
    sEvents_sysmisc,
};

static const u16 sEventFolderFlatCounts[] =
{
    ARRAY_COUNT(sEvents_early),
    0,
    ARRAY_COUNT(sEvents_badges),
    ARRAY_COUNT(sEvents_hms),
    0,
    ARRAY_COUNT(sEvents_legends),
    0,
    0,
    ARRAY_COUNT(sEvents_sysmisc),
};

static const struct RhDebugEvent * const sEventKantoTables[] =
{
    sEvents_k_mtmoon,
    sEvents_k_nugget,
    sEvents_k_bill,
    sEvents_k_cerulean,
    sEvents_k_anne,
    sEvents_k_rockets,
    sEvents_k_fuji,
    sEvents_k_snorlax,
    sEvents_k_silph,
    sEvents_k_plant,
    sEvents_k_seafoam,
    sEvents_k_cinnabar,
    sEvents_k_viridian,
    sEvents_k_vr,
    sEvents_k_miscrocket,
};

static const u16 sEventKantoCounts[] =
{
    ARRAY_COUNT(sEvents_k_mtmoon),
    ARRAY_COUNT(sEvents_k_nugget),
    ARRAY_COUNT(sEvents_k_bill),
    ARRAY_COUNT(sEvents_k_cerulean),
    ARRAY_COUNT(sEvents_k_anne),
    ARRAY_COUNT(sEvents_k_rockets),
    ARRAY_COUNT(sEvents_k_fuji),
    ARRAY_COUNT(sEvents_k_snorlax),
    ARRAY_COUNT(sEvents_k_silph),
    ARRAY_COUNT(sEvents_k_plant),
    ARRAY_COUNT(sEvents_k_seafoam),
    ARRAY_COUNT(sEvents_k_cinnabar),
    ARRAY_COUNT(sEvents_k_viridian),
    ARRAY_COUNT(sEvents_k_vr),
    ARRAY_COUNT(sEvents_k_miscrocket),
};

static const struct RhDebugEvent * const sEventSideTables[] =
{
    sEvents_s_trades,
    sEvents_s_tutors,
    sEvents_s_gymtms,
    sEvents_s_aides,
    sEvents_s_fanclub,
    sEvents_s_daycare,
    sEvents_s_misc,
};

static const u16 sEventSideCounts[] =
{
    ARRAY_COUNT(sEvents_s_trades),
    ARRAY_COUNT(sEvents_s_tutors),
    ARRAY_COUNT(sEvents_s_gymtms),
    ARRAY_COUNT(sEvents_s_aides),
    ARRAY_COUNT(sEvents_s_fanclub),
    ARRAY_COUNT(sEvents_s_daycare),
    ARRAY_COUNT(sEvents_s_misc),
};

static const struct RhDebugEvent * const sEventSeviiTables[] =
{
    sEvents_v_sys,
    sEvents_v_tickets,
    sEvents_v_celio,
    sEvents_v_lostelle,
    sEvents_v_rockets,
    sEvents_v_selphy,
    sEvents_v_ruin,
    sEvents_v_rivals,
    sEvents_v_misc,
};

static const u16 sEventSeviiCounts[] =
{
    ARRAY_COUNT(sEvents_v_sys),
    ARRAY_COUNT(sEvents_v_tickets),
    ARRAY_COUNT(sEvents_v_celio),
    ARRAY_COUNT(sEvents_v_lostelle),
    ARRAY_COUNT(sEvents_v_rockets),
    ARRAY_COUNT(sEvents_v_selphy),
    ARRAY_COUNT(sEvents_v_ruin),
    ARRAY_COUNT(sEvents_v_rivals),
    ARRAY_COUNT(sEvents_v_misc),
};

static const struct RhDebugEvent * const sEventMapTables[] =
{
    sEvents_w_towns,
    sEvents_w_dung,
    sEvents_w_sevii,
};

static const u16 sEventMapCounts[] =
{
    ARRAY_COUNT(sEvents_w_towns),
    ARRAY_COUNT(sEvents_w_dung),
    ARRAY_COUNT(sEvents_w_sevii),
};

// Total events: 368
